import type { DataStore } from "./types.js";
import { buildGeography } from "./geo-seed.js";

const now = () => new Date().toISOString();

/** Well-known local demo accounts — never auto-delete matching production users. */
export const DEMO_ACCOUNT_EMAILS = [
  "admin@nusa.business",
  "agent@nusa.business",
  "owner@example.com",
] as const;

/**
 * Geography-only store for production / empty bootstrap.
 * No demo users, businesses, reviews, bookings, or vendors.
 */
export function createReferenceStore(): DataStore {
  const full = createSeed();
  return {
    islands: full.islands,
    places: full.places,
    businesses: [],
    users: [],
    claims: [],
    reviews: [],
    bookings: [],
    vendors: [],
    invites: [],
    recoveryTokens: [],
    reports: [],
  };
}

/** Full local/demo catalog (geography + sample listings + demo users). */
export function createSeed(): DataStore {
  const t = now();

  const { islands, places: adminAndAreas } = buildGeography();

  const places = adminAndAreas;

  const users = [
    {
      id: "usr-admin",
      email: "admin@nusa.business",
      name: "Nusa Admin",
      role: "admin" as const,
      password: "admin123",
    },
    {
      id: "usr-agent",
      email: "agent@nusa.business",
      name: "Field Agent Bali",
      role: "field_agent" as const,
      password: "agent123",
    },
    {
      id: "usr-owner",
      email: "owner@example.com",
      name: "Listing Owner",
      role: "owner" as const,
      password: "owner123",
    },
  ];

  const biz = (
    partial: Omit<
      DataStore["businesses"][number],
      "gallery" | "openingHours" | "faq" | "createdAt" | "updatedAt" | "status"
    > & {
      status?: DataStore["businesses"][number]["status"];
      openingHours?: DataStore["businesses"][number]["openingHours"];
    },
  ) => ({
    gallery: [],
    openingHours: [
      { day: "Mon", open: "09:00", close: "21:00" },
      { day: "Tue", open: "09:00", close: "21:00" },
      { day: "Wed", open: "09:00", close: "21:00" },
      { day: "Thu", open: "09:00", close: "21:00" },
      { day: "Fri", open: "09:00", close: "22:00" },
      { day: "Sat", open: "09:00", close: "22:00" },
      { day: "Sun", open: "10:00", close: "21:00" },
    ],
    faq: [],
    createdAt: t,
    updatedAt: t,
    status: partial.status ?? ("published" as const),
    sample: partial.sample ?? true,
    ...partial,
  });

  const hours24 = [
    { day: "Mon", open: "00:00", close: "24:00" },
    { day: "Tue", open: "00:00", close: "24:00" },
    { day: "Wed", open: "00:00", close: "24:00" },
    { day: "Thu", open: "00:00", close: "24:00" },
    { day: "Fri", open: "00:00", close: "24:00" },
    { day: "Sat", open: "00:00", close: "24:00" },
    { day: "Sun", open: "00:00", close: "24:00" },
  ];

  const businesses = [
    biz({
      id: "biz-single-fin",
      placeId: "pl-uluwatu",
      slug: "single-fin-uluwatu",
      name: "Single Fin Uluwatu",
      categories: ["cafes-coffee-shops", "bars-pubs"],
      facets: {
        cuisine: ["western"],
        meal: ["breakfast", "brunch", "lunch", "dinner"],
        setting: ["beachfront"],
        features: ["ocean-view"],
        alcohol: ["cocktails"],
      },
      summary: "Cliffside surf café above Uluwatu.",
      description:
        "Iconic surf hangout with ocean views, cold drinks, and sunset energy.",
      address: "Jl. Pura Luhur Uluwatu, Pecatu",
      phone: "+62 361 0001001",
      website: "https://example.com/single-fin-uluwatu",
      bookingMode: "none",
      lat: -8.8291,
      lng: 115.0849,
    }),
    biz({
      id: "biz-kecak",
      placeId: "pl-uluwatu",
      slug: "uluwatu-temple-kecak",
      name: "Uluwatu Temple Kecak",
      categories: ["cultural-experiences", "tourist-attractions"],
      facets: { activity: ["cultural"], duration: ["under-2-hours"], format: ["large-group"] },
      summary: "Sunset kecak and fire dance at the temple cliffs.",
      description: "Cultural performance operator for Uluwatu sunset shows.",
      bookingMode: "event",
      lat: -8.8295,
      lng: 115.0845,
    }),
    biz({
      id: "biz-alchemy",
      placeId: "pl-uluwatu",
      slug: "alchemy-uluwatu",
      name: "Alchemy Uluwatu",
      categories: ["vegetarian-vegan-dining", "cafes-coffee-shops"],
      facets: {
        cuisine: ["western"],
        dietary: ["vegetarian", "vegan", "organic"],
        meal: ["breakfast", "brunch", "lunch"],
        food_type: ["healthy-food"],
      },
      summary: "Plant-based wellness café and juice bar.",
      description: "Cold-pressed juices, bowls, and wellness-minded dining.",
      bookingMode: "service",
      lat: -8.821,
      lng: 115.088,
    }),
    biz({
      id: "biz-menega",
      placeId: "pl-jimbaran",
      slug: "menega-cafe",
      name: "Menega Cafe",
      categories: ["seafood-restaurants"],
      facets: {
        cuisine: ["indonesian"],
        food_type: ["seafood"],
        setting: ["beachfront"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in"],
      },
      summary: "Jimbaran beach seafood institution.",
      description: "Grilled seafood on the sand with bay views.",
      bookingMode: "service",
      lat: -8.784,
      lng: 115.163,
    }),
    biz({
      id: "biz-fish-tours",
      placeId: "pl-jimbaran",
      slug: "jimbaran-fish-market-tours",
      name: "Jimbaran Fish Market Tours",
      categories: ["tour-operators-local-guides"],
      summary: "Local market and seafood culture tours.",
      description: "Guided morning walks through Jimbaran’s fish market.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-spa-jim",
      placeId: "pl-jimbaran",
      slug: "spa-jimbaran-bay",
      name: "Spa Jimbaran Bay",
      categories: ["spas-massage"],
      summary: "Bay-side spa treatments.",
      description: "Massage and spa packages near Jimbaran Bay.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-pande-egi",
      placeId: "pl-gianyar",
      slug: "babi-guling-pande-egi",
      name: "Babi Guling Pande Egi",
      categories: ["warungs-local-food"],
      facets: {
        cuisine: ["balinese", "indonesian"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in", "takeaway"],
        food_type: ["street-food"],
      },
      summary: "Iconic Gianyar babi guling.",
      description:
        "Local favourite for Balinese roast pork — a must when visiting Gianyar.",
      address: "Jl. Ngurah Rai 12, Gianyar",
      whatsapp: "+62 812 0000001",
      gallery: [
        "/listings/pande-egi-1.svg",
        "/listings/pande-egi-2.svg",
        "/listings/pande-egi-3.svg",
      ],
      bookingMode: "none",
      registeredByAgentId: "usr-agent",
      lat: -8.5439,
      lng: 115.325,
    }),
    biz({
      id: "biz-kopi-rai",
      placeId: "pl-gianyar",
      slug: "kopi-ngurah-rai",
      name: "Kopi Ngurah Rai",
      categories: ["cafes-coffee-shops"],
      facets: {
        cuisine: ["indonesian"],
        meal: ["breakfast", "brunch"],
        food_type: ["coffee"],
        dietary: ["halal"],
      },
      summary: "Neighbour coffee stall in the same ruko row.",
      description: "Espresso and Bali kopi next door to the babi guling counters.",
      address: "Jl. Ngurah Rai 12, Gianyar",
      whatsapp: "+62 812 0000012",
      bookingMode: "none",
      lat: -8.5439,
      lng: 115.325,
    }),
    biz({
      id: "biz-celuk",
      placeId: "pl-gianyar",
      slug: "celuk-silver-workshop",
      name: "Celuk Silver Workshop",
      categories: ["jewelry-accessories", "souvenirs-handicrafts"],
      summary: "Traditional silversmith workshop in Celuk.",
      description: "Handcrafted silver jewellery and workshop visits.",
      address: "Jl. Raya Celuk, Gianyar",
      bookingMode: "service",
      vendorId: "vnd-celuk",
      lat: -8.5485,
      lng: 115.318,
    }),
    biz({
      id: "biz-batik-g",
      placeId: "pl-gianyar",
      slug: "batik-gianyar-gallery",
      name: "Batik Gianyar Gallery",
      categories: ["fashion-clothing", "souvenirs-handicrafts"],
      summary: "Batik textiles and gallery.",
      description: "Local batik makers and showroom in Gianyar.",
      address: "Jl. Dharma Giri, Gianyar",
      bookingMode: "none",
      vendorId: "vnd-batik",
      lat: -8.5412,
      lng: 115.331,
    }),
    biz({
      id: "biz-warung-pasar",
      placeId: "pl-gianyar",
      slug: "warung-pasar-gianyar",
      name: "Warung Pasar Gianyar",
      categories: ["warungs-local-food"],
      summary: "Market warung for local lunch plates.",
      description: "Simple nasi campur and sayur within walking distance of the centre.",
      address: "Pasar Gianyar",
      bookingMode: "none",
      lat: -8.5455,
      lng: 115.3275,
    }),
    biz({
      id: "biz-bpr-gianyar",
      placeId: "pl-gianyar",
      slug: "bpr-gianyar-pusat",
      name: "BPR Gianyar Pusat",
      categories: ["banks-atms"],
      summary: "Local bank branch for everyday banking.",
      description: "Community bank counter near Gianyar town centre.",
      address: "Jl. Ngurah Rai 40, Gianyar",
      bookingMode: "none",
      lat: -8.5448,
      lng: 115.3262,
    }),
    biz({
      id: "biz-klinik-g",
      placeId: "pl-gianyar",
      slug: "klinik-sehat-gianyar",
      name: "Klinik Sehat Gianyar",
      categories: ["clinics-hospitals", "pharmacies"],
      facets: {
        availability: ["24-hours"],
        specialty: ["general-practice"],
        facility: ["pharmacy"],
        hours: ["24-hour-pharmacy", "24-hour-clinic"],
        care_mode: ["in-clinic"],
      },
      summary: "Neighbourhood clinic and apotek counter.",
      description: "General practice and basic pharmacy services. Open 24 hours.",
      address: "Jl. Bypass Dharma Giri",
      bookingMode: "service",
      openingHours: hours24,
      lat: -8.54,
      lng: 115.329,
    }),
    biz({
      id: "biz-gianyar-weddings",
      placeId: "pl-gianyar",
      slug: "gianyar-wedding-organizer",
      name: "Gianyar Wedding Organizer",
      categories: ["wedding-planners"],
      summary: "Local ceremony planning for Gianyar and Ubud.",
      description: "Wedding planning with related catering, flowers, and cakes via partner listings.",
      address: "Jl. Dharma Giri, Gianyar",
      bookingMode: "event",
      lat: -8.542,
      lng: 115.328,
    }),
    biz({
      id: "biz-gianyar-catering",
      placeId: "pl-gianyar",
      slug: "ibu-made-catering",
      name: "Ibu Made Catering",
      categories: ["catering-services"],
      summary: "Balinese catering for ceremonies and events.",
      description: "Buffets and boxed meals — listed under Food & Drink, shown as related on Events.",
      address: "Gianyar town",
      bookingMode: "service",
      lat: -8.543,
      lng: 115.327,
    }),
    biz({
      id: "biz-ibu-oka",
      placeId: "pl-ubud",
      slug: "warung-babi-guling-ibu-oka",
      name: "Warung Babi Guling Ibu Oka",
      categories: ["warungs-local-food"],
      facets: {
        cuisine: ["balinese", "indonesian"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in"],
        food_type: ["street-food"],
      },
      summary: "Famous Ubud babi guling warung.",
      description: "Classic Balinese roast pork in central Ubud.",
      address: "Jalan Suweta, Ubud",
      bookingMode: "none",
      lat: -8.5069,
      lng: 115.2625,
    }),
    biz({
      id: "biz-yoga-barn",
      placeId: "pl-ubud",
      slug: "yoga-barn-ubud",
      name: "Yoga Barn Ubud",
      categories: ["yoga-pilates-studios"],
      summary: "Wellness classes and yoga community hub.",
      description: "Drop-in classes, workshops, and wellness events.",
      address: "Pengosekan, Ubud",
      bookingMode: "service",
      lat: -8.5195,
      lng: 115.265,
    }),
    biz({
      id: "biz-monkey-cafe",
      placeId: "pl-ubud",
      slug: "sacred-monkey-forest-cafe",
      name: "Sacred Monkey Forest Cafe",
      categories: ["cafes-coffee-shops"],
      summary: "Café near the monkey forest sanctuary.",
      description: "Casual café for visitors exploring the sanctuary.",
      bookingMode: "none",
      lat: -8.5188,
      lng: 115.2594,
    }),
    biz({
      id: "biz-old-mans",
      placeId: "pl-canggu",
      slug: "old-mans-canggu",
      name: "Old Man's Canggu",
      categories: ["bars-pubs", "beach-clubs"],
      summary: "Beachside F&B and surf culture.",
      description: "Canggu beach hangout with food, drinks, and sunset vibes.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-surf-canggu",
      placeId: "pl-canggu",
      slug: "canggu-surf-school",
      name: "Canggu Surf School",
      categories: ["surf-schools-rentals"],
      facets: {
        activity: ["surfing"],
        skill_level: ["beginner", "intermediate"],
        duration: ["half-day"],
        pickup: ["meeting-point"],
      },
      summary: "Surf lessons for all levels.",
      description: "Board rental and lessons on Canggu breaks.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-cowork",
      placeId: "pl-canggu",
      slug: "digital-nomad-cowork-canggu",
      name: "Digital Nomad Cowork Canggu",
      categories: ["coworking-spaces"],
      summary: "Coworking for remote workers.",
      description: "Desks, wifi, and community events in Canggu.",
      bookingMode: "rental",
    }),
    biz({
      id: "biz-gudeg",
      placeId: "pl-yogya",
      slug: "gudeg-yu-djum",
      name: "Gudeg Yu Djum",
      categories: ["warungs-local-food"],
      facets: { cuisine: ["javanese", "indonesian"], dietary: ["halal"], meal: ["lunch"] },
      summary: "Classic Yogyakarta gudeg.",
      description: "Legendary jackfruit stew institution.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-batik-malio",
      placeId: "pl-yogya",
      slug: "batik-malioboro-house",
      name: "Batik Malioboro House",
      categories: ["fashion-clothing", "souvenirs-handicrafts"],
      summary: "Batik near Malioboro.",
      description: "Retail batik and textiles in Yogyakarta.",
      bookingMode: "none",
      vendorId: "vnd-malio",
    }),
    biz({
      id: "biz-boro",
      placeId: "pl-yogya",
      slug: "borobudur-sunrise-tours",
      name: "Borobudur Sunrise Tours",
      categories: ["tour-operators-local-guides"],
      summary: "Sunrise temple tours from Yogyakarta.",
      description: "Guided early-morning Borobudur experiences.",
      bookingMode: "event",
    }),
    biz({
      id: "biz-scuba",
      placeId: "pl-gili-t",
      slug: "scuba-republic-gili",
      name: "Scuba Republic Gili",
      categories: ["diving-snorkeling"],
      facets: {
        activity: ["diving", "snorkeling"],
        certification: ["padi"],
        duration: ["half-day", "full-day"],
        skill_level: ["beginner", "intermediate", "advanced"],
      },
      summary: "Diving centre on Gili Trawangan.",
      description: "Fun dives and courses around the Gilis.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-coto",
      placeId: "pl-makassar",
      slug: "coto-makassar-warung",
      name: "Coto Makassar Warung",
      categories: ["warungs-local-food"],
      summary: "Traditional Makassar coto.",
      description: "Local beef stew warung favourites.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-nusa-dua-beach",
      placeId: "pl-nusa-dua",
      slug: "nusa-dua-beach-hotel",
      name: "Nusa Dua Beach Hotel",
      categories: ["hotels"],
      facets: {
        property_type: ["hotel"],
        star_rating: ["4"],
        location_feature: ["beachfront", "ocean-view"],
        facilities: ["pool", "restaurant", "spa"],
        meal_plan: ["breakfast-included"],
      },
      summary: "Beachfront hotel on the Nusa Dua peninsula.",
      description: "Ocean-front rooms, pool, and a quiet lagoon beach.",
      address: "Kawasan Pariwisata Nusa Dua",
      bookingMode: "rental",
      lat: -8.8009,
      lng: 115.2324,
    }),
    biz({
      id: "biz-canggu-scooter",
      placeId: "pl-canggu",
      slug: "canggu-scooter-rental",
      name: "Canggu Scooter Rental",
      categories: ["motorcycle-scooter-rentals"],
      facets: {
        vehicle_type: ["scooter", "motorcycle"],
        rental_type: ["self-drive", "daily", "weekly"],
        transmission: ["automatic"],
        rental_features: ["helmet-included", "insurance-included"],
      },
      summary: "Daily scooter hire in Canggu.",
      description: "Automatic scooters with helmets, delivered in the Canggu area.",
      address: "Jl. Pantai Batu Bolong, Canggu",
      bookingMode: "rental",
      lat: -8.6478,
      lng: 115.1385,
    }),
    biz({
      id: "biz-denpasar-halal",
      placeId: "pl-denpasar",
      slug: "rumah-makan-halal-denpasar",
      name: "Rumah Makan Halal Denpasar",
      categories: ["restaurants"],
      facets: {
        cuisine: ["indonesian"],
        dietary: ["halal"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in", "takeaway"],
      },
      summary: "Halal Indonesian restaurant in Denpasar.",
      description: "Certified halal kitchen serving Indonesian plates in the city.",
      address: "Jl. Teuku Umar, Denpasar",
      bookingMode: "none",
      lat: -8.6724,
      lng: 115.2126,
    }),
  ];

  const vendors = [
    {
      id: "vnd-celuk",
      businessId: "biz-celuk",
      name: "Celuk Silver Shop",
      slug: "celuk-silver-shop",
      description: "Handmade silver from the Celuk workshop.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-ring",
          name: "Silver Ring",
          slug: "silver-ring",
          price: 250000,
          currency: "IDR",
          stock: 24,
          description: "Handcrafted sterling silver ring.",
        },
        {
          id: "prd-necklace",
          name: "Silver Necklace",
          slug: "silver-necklace",
          price: 450000,
          currency: "IDR",
          stock: 12,
          description: "Traditional Celuk necklace.",
        },
      ],
    },
    {
      id: "vnd-batik",
      businessId: "biz-batik-g",
      name: "Gianyar Batik Store",
      slug: "gianyar-batik-store",
      description: "Batik cloth and ready-to-wear.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-batik-cloth",
          name: "Batik Cloth",
          slug: "batik-cloth",
          price: 350000,
          currency: "IDR",
          stock: 40,
          description: "Hand-stamped batik fabric.",
        },
      ],
    },
    {
      id: "vnd-malio",
      businessId: "biz-batik-malio",
      name: "Malioboro Batik Store",
      slug: "malioboro-batik-store",
      description: "Yogya batik for visitors.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-shirt",
          name: "Batik Shirt",
          slug: "batik-shirt",
          price: 275000,
          currency: "IDR",
          stock: 30,
          description: "Ready-to-wear batik shirt.",
        },
      ],
    },
  ];

  const reviews = [
    {
      id: "rev-1",
      businessId: "biz-pande-egi",
      authorName: "Maya",
      service: 5,
      value: 5,
      location: 4,
      cleanliness: 4,
      comment: "Best babi guling we found in Gianyar.",
      createdAt: t,
    },
    {
      id: "rev-2",
      businessId: "biz-single-fin",
      authorName: "Tom",
      service: 4,
      value: 3,
      location: 5,
      cleanliness: 4,
      comment: "Unbeatable view after a surf session.",
      createdAt: t,
    },
  ];

  return {
    islands,
    places,
    businesses,
    users,
    claims: [],
    reviews,
    bookings: [],
    vendors,
    invites: [],
    recoveryTokens: [],
    reports: [],
  };
}
