import type { DataStore } from "./types.js";
import { buildGeography } from "./geo-seed.js";

const now = () => new Date().toISOString();

/** Well-known local demo accounts — never auto-delete matching production users. */
export const DEMO_ACCOUNT_EMAILS = [
  "admin@nusa.business",
  "agent@nusa.business",
  "owner@example.com",
] as const;

/**
 * Geography-only store for production / empty bootstrap.
 * No demo users, businesses, reviews, bookings, or vendors.
 */
export function createReferenceStore(): DataStore {
  const full = createSeed();
  return {
    islands: full.islands,
    places: full.places,
    businesses: [],
    users: [],
    claims: [],
    reviews: [],
    bookings: [],
    vendors: [],
    invites: [],
    recoveryTokens: [],
    reports: [],
  };
}

/** Full local/demo catalog (geography + sample listings + demo users). */
export function createSeed(): DataStore {
  const t = now();

  const { islands, places: adminAndAreas } = buildGeography();

  const places = adminAndAreas;

  const users = [
    {
      id: "usr-admin",
      email: "admin@nusa.business",
      name: "Nusa Admin",
      role: "admin" as const,
      password: "admin123",
    },
    {
      id: "usr-agent",
      email: "agent@nusa.business",
      name: "Field Agent Bali",
      role: "field_agent" as const,
      password: "agent123",
    },
    {
      id: "usr-owner",
      email: "owner@example.com",
      name: "Listing Owner",
      role: "owner" as const,
      password: "owner123",
    },
  ];

  const biz = (
    partial: Omit<
      DataStore["businesses"][number],
      "gallery" | "openingHours" | "faq" | "createdAt" | "updatedAt" | "status"
    > & {
      status?: DataStore["businesses"][number]["status"];
      openingHours?: DataStore["businesses"][number]["openingHours"];
    },
  ) => ({
    gallery: [],
    openingHours: [
      { day: "Mon", open: "09:00", close: "21:00" },
      { day: "Tue", open: "09:00", close: "21:00" },
      { day: "Wed", open: "09:00", close: "21:00" },
      { day: "Thu", open: "09:00", close: "21:00" },
      { day: "Fri", open: "09:00", close: "22:00" },
      { day: "Sat", open: "09:00", close: "22:00" },
      { day: "Sun", open: "10:00", close: "21:00" },
    ],
    faq: [],
    createdAt: t,
    updatedAt: t,
    status: partial.status ?? ("published" as const),
    sample: partial.sample ?? true,
    ...partial,
  });

  const hours24 = [
    { day: "Mon", open: "00:00", close: "24:00" },
    { day: "Tue", open: "00:00", close: "24:00" },
    { day: "Wed", open: "00:00", close: "24:00" },
    { day: "Thu", open: "00:00", close: "24:00" },
    { day: "Fri", open: "00:00", close: "24:00" },
    { day: "Sat", open: "00:00", close: "24:00" },
    { day: "Sun", open: "00:00", close: "24:00" },
  ];

  const businesses = [
    biz({
      id: "biz-single-fin",
      placeId: "pl-uluwatu",
      slug: "single-fin-uluwatu",
      name: "Single Fin Uluwatu",
      categories: ["cafes-coffee-shops", "bars-pubs"],
      facets: {
        cuisine: ["western"],
        meal: ["breakfast", "brunch", "lunch", "dinner"],
        setting: ["beachfront"],
        features: ["ocean-view"],
        alcohol: ["cocktails"],
      },
      summary: "Cliffside surf café above Uluwatu.",
      description:
        "Iconic surf hangout with ocean views, cold drinks, and sunset energy.",
      address: "Jl. Pura Luhur Uluwatu, Pecatu",
      phone: "+62 361 0001001",
      website: "https://example.com/single-fin-uluwatu",
      bookingMode: "none",
      lat: -8.8291,
      lng: 115.0849,
    }),
    biz({
      id: "biz-kecak",
      placeId: "pl-uluwatu",
      slug: "uluwatu-temple-kecak",
      name: "Uluwatu Temple Kecak",
      categories: ["cultural-experiences", "tourist-attractions"],
      facets: { activity: ["cultural"], duration: ["under-2-hours"], format: ["large-group"] },
      summary: "Sunset kecak and fire dance at the temple cliffs.",
      description: "Cultural performance operator for Uluwatu sunset shows.",
      bookingMode: "event",
      lat: -8.8295,
      lng: 115.0845,
    }),
    biz({
      id: "biz-alchemy",
      placeId: "pl-uluwatu",
      slug: "alchemy-uluwatu",
      name: "Alchemy Uluwatu",
      categories: ["vegetarian-vegan-dining", "cafes-coffee-shops"],
      facets: {
        cuisine: ["western"],
        dietary: ["vegetarian", "vegan", "organic"],
        meal: ["breakfast", "brunch", "lunch"],
        food_type: ["healthy-food"],
      },
      summary: "Plant-based wellness café and juice bar.",
      description: "Cold-pressed juices, bowls, and wellness-minded dining.",
      bookingMode: "service",
      lat: -8.821,
      lng: 115.088,
    }),
    biz({
      id: "biz-menega",
      placeId: "pl-jimbaran",
      slug: "menega-cafe",
      name: "Menega Cafe",
      categories: ["seafood-restaurants"],
      facets: {
        cuisine: ["indonesian"],
        food_type: ["seafood"],
        setting: ["beachfront"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in"],
      },
      summary: "Jimbaran beach seafood institution.",
      description: "Grilled seafood on the sand with bay views.",
      bookingMode: "service",
      lat: -8.784,
      lng: 115.163,
    }),
    biz({
      id: "biz-fish-tours",
      placeId: "pl-jimbaran",
      slug: "jimbaran-fish-market-tours",
      name: "Jimbaran Fish Market Tours",
      categories: ["tour-operators-local-guides"],
      summary: "Local market and seafood culture tours.",
      description: "Guided morning walks through Jimbaran’s fish market.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-spa-jim",
      placeId: "pl-jimbaran",
      slug: "spa-jimbaran-bay",
      name: "Spa Jimbaran Bay",
      categories: ["spas-massage"],
      summary: "Bay-side spa treatments.",
      description: "Massage and spa packages near Jimbaran Bay.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-pande-egi",
      placeId: "pl-gianyar",
      slug: "babi-guling-pande-egi",
      name: "Babi Guling Pande Egi",
      categories: ["warungs-local-food"],
      facets: {
        cuisine: ["balinese", "indonesian"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in", "takeaway"],
        food_type: ["street-food"],
      },
      summary: "Iconic Gianyar babi guling.",
      description:
        "Local favourite for Balinese roast pork — a must when visiting Gianyar.",
      address: "Jl. Ngurah Rai 12, Gianyar",
      whatsapp: "+62 812 0000001",
      bookingMode: "none",
      registeredByAgentId: "usr-agent",
      lat: -8.5439,
      lng: 115.325,
    }),
    biz({
      id: "biz-kopi-rai",
      placeId: "pl-gianyar",
      slug: "kopi-ngurah-rai",
      name: "Kopi Ngurah Rai",
      categories: ["cafes-coffee-shops"],
      facets: {
        cuisine: ["indonesian"],
        meal: ["breakfast", "brunch"],
        food_type: ["coffee"],
        dietary: ["halal"],
      },
      summary: "Neighbour coffee stall in the same ruko row.",
      description: "Espresso and Bali kopi next door to the babi guling counters.",
      address: "Jl. Ngurah Rai 12, Gianyar",
      whatsapp: "+62 812 0000012",
      bookingMode: "none",
      lat: -8.5439,
      lng: 115.325,
    }),
    biz({
      id: "biz-celuk",
      placeId: "pl-gianyar",
      slug: "celuk-silver-workshop",
      name: "Celuk Silver Workshop",
      categories: ["jewelry-accessories", "souvenirs-handicrafts"],
      summary: "Traditional silversmith workshop in Celuk.",
      description: "Handcrafted silver jewellery and workshop visits.",
      address: "Jl. Raya Celuk, Gianyar",
      bookingMode: "service",
      vendorId: "vnd-celuk",
      lat: -8.5485,
      lng: 115.318,
    }),
    biz({
      id: "biz-batik-g",
      placeId: "pl-gianyar",
      slug: "batik-gianyar-gallery",
      name: "Batik Gianyar Gallery",
      categories: ["fashion-clothing", "souvenirs-handicrafts"],
      summary: "Batik textiles and gallery.",
      description: "Local batik makers and showroom in Gianyar.",
      address: "Jl. Dharma Giri, Gianyar",
      bookingMode: "none",
      vendorId: "vnd-batik",
      lat: -8.5412,
      lng: 115.331,
    }),
    biz({
      id: "biz-warung-pasar",
      placeId: "pl-gianyar",
      slug: "warung-pasar-gianyar",
      name: "Warung Pasar Gianyar",
      categories: ["warungs-local-food"],
      summary: "Market warung for local lunch plates.",
      description: "Simple nasi campur and sayur within walking distance of the centre.",
      address: "Pasar Gianyar",
      bookingMode: "none",
      lat: -8.5455,
      lng: 115.3275,
    }),
    biz({
      id: "biz-bpr-gianyar",
      placeId: "pl-gianyar",
      slug: "bpr-gianyar-pusat",
      name: "BPR Gianyar Pusat",
      categories: ["banks-atms"],
      summary: "Local bank branch for everyday banking.",
      description: "Community bank counter near Gianyar town centre.",
      address: "Jl. Ngurah Rai 40, Gianyar",
      bookingMode: "none",
      lat: -8.5448,
      lng: 115.3262,
    }),
    biz({
      id: "biz-klinik-g",
      placeId: "pl-gianyar",
      slug: "klinik-sehat-gianyar",
      name: "Klinik Sehat Gianyar",
      categories: ["clinics-hospitals", "pharmacies"],
      facets: {
        availability: ["24-hours"],
        specialty: ["general-practice"],
        facility: ["pharmacy"],
        hours: ["24-hour-pharmacy", "24-hour-clinic"],
        care_mode: ["in-clinic"],
      },
      summary: "Neighbourhood clinic and apotek counter.",
      description: "General practice and basic pharmacy services. Open 24 hours.",
      address: "Jl. Bypass Dharma Giri",
      bookingMode: "service",
      openingHours: hours24,
      lat: -8.54,
      lng: 115.329,
    }),
    biz({
      id: "biz-gianyar-weddings",
      placeId: "pl-gianyar",
      slug: "gianyar-wedding-organizer",
      name: "Gianyar Wedding Organizer",
      categories: ["wedding-planners"],
      summary: "Local ceremony planning for Gianyar and Ubud.",
      description: "Wedding planning with related catering, flowers, and cakes via partner listings.",
      address: "Jl. Dharma Giri, Gianyar",
      bookingMode: "event",
      lat: -8.542,
      lng: 115.328,
    }),
    biz({
      id: "biz-gianyar-catering",
      placeId: "pl-gianyar",
      slug: "ibu-made-catering",
      name: "Ibu Made Catering",
      categories: ["catering-services"],
      summary: "Balinese catering for ceremonies and events.",
      description: "Buffets and boxed meals — listed under Food & Drink, shown as related on Events.",
      address: "Gianyar town",
      bookingMode: "service",
      lat: -8.543,
      lng: 115.327,
    }),
    biz({
      id: "biz-ibu-oka",
      placeId: "pl-ubud",
      slug: "warung-babi-guling-ibu-oka",
      name: "Warung Babi Guling Ibu Oka",
      categories: ["warungs-local-food"],
      facets: {
        cuisine: ["balinese", "indonesian"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in"],
        food_type: ["street-food"],
      },
      summary: "Famous Ubud babi guling warung.",
      description: "Classic Balinese roast pork in central Ubud.",
      address: "Jalan Suweta, Ubud",
      bookingMode: "none",
      lat: -8.5069,
      lng: 115.2625,
    }),
    biz({
      id: "biz-yoga-barn",
      placeId: "pl-ubud",
      slug: "yoga-barn-ubud",
      name: "Yoga Barn Ubud",
      categories: ["yoga-pilates-studios"],
      summary: "Wellness classes and yoga community hub.",
      description: "Drop-in classes, workshops, and wellness events.",
      address: "Pengosekan, Ubud",
      bookingMode: "service",
      lat: -8.5195,
      lng: 115.265,
    }),
    biz({
      id: "biz-monkey-cafe",
      placeId: "pl-ubud",
      slug: "sacred-monkey-forest-cafe",
      name: "Sacred Monkey Forest Cafe",
      categories: ["cafes-coffee-shops"],
      summary: "Café near the monkey forest sanctuary.",
      description: "Casual café for visitors exploring the sanctuary.",
      bookingMode: "none",
      lat: -8.5188,
      lng: 115.2594,
    }),
    biz({
      id: "biz-old-mans",
      placeId: "pl-canggu",
      slug: "old-mans-canggu",
      name: "Old Man's Canggu",
      categories: ["bars-pubs", "beach-clubs"],
      summary: "Beachside F&B and surf culture.",
      description: "Canggu beach hangout with food, drinks, and sunset vibes.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-surf-canggu",
      placeId: "pl-canggu",
      slug: "canggu-surf-school",
      name: "Canggu Surf School",
      categories: ["surf-schools-rentals"],
      facets: {
        activity: ["surfing"],
        skill_level: ["beginner", "intermediate"],
        duration: ["half-day"],
        pickup: ["meeting-point"],
      },
      summary: "Surf lessons for all levels.",
      description: "Board rental and lessons on Canggu breaks.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-cowork",
      placeId: "pl-canggu",
      slug: "digital-nomad-cowork-canggu",
      name: "Digital Nomad Cowork Canggu",
      categories: ["coworking-spaces"],
      summary: "Coworking for remote workers.",
      description: "Desks, wifi, and community events in Canggu.",
      bookingMode: "rental",
    }),
    biz({
      id: "biz-gudeg",
      placeId: "pl-yogya",
      slug: "gudeg-yu-djum",
      name: "Gudeg Yu Djum",
      categories: ["warungs-local-food"],
      facets: { cuisine: ["javanese", "indonesian"], dietary: ["halal"], meal: ["lunch"] },
      summary: "Classic Yogyakarta gudeg.",
      description: "Legendary jackfruit stew institution.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-batik-malio",
      placeId: "pl-yogya",
      slug: "batik-malioboro-house",
      name: "Batik Malioboro House",
      categories: ["fashion-clothing", "souvenirs-handicrafts"],
      summary: "Batik near Malioboro.",
      description: "Retail batik and textiles in Yogyakarta.",
      bookingMode: "none",
      vendorId: "vnd-malio",
    }),
    biz({
      id: "biz-boro",
      placeId: "pl-yogya",
      slug: "borobudur-sunrise-tours",
      name: "Borobudur Sunrise Tours",
      categories: ["tour-operators-local-guides"],
      summary: "Sunrise temple tours from Yogyakarta.",
      description: "Guided early-morning Borobudur experiences.",
      bookingMode: "event",
    }),
    biz({
      id: "biz-scuba",
      placeId: "pl-gili-t",
      slug: "scuba-republic-gili",
      name: "Scuba Republic Gili",
      categories: ["diving-snorkeling"],
      facets: {
        activity: ["diving", "snorkeling"],
        certification: ["padi"],
        duration: ["half-day", "full-day"],
        skill_level: ["beginner", "intermediate", "advanced"],
      },
      summary: "Diving centre on Gili Trawangan.",
      description: "Fun dives and courses around the Gilis.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-coto",
      placeId: "pl-makassar",
      slug: "coto-makassar-warung",
      name: "Coto Makassar Warung",
      categories: ["warungs-local-food"],
      summary: "Traditional Makassar coto.",
      description: "Local beef stew warung favourites.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-nusa-dua-beach",
      placeId: "pl-nusa-dua",
      slug: "nusa-dua-beach-hotel",
      name: "Nusa Dua Beach Hotel",
      categories: ["hotels"],
      facets: {
        property_type: ["hotel"],
        star_rating: ["4"],
        location_feature: ["beachfront", "ocean-view"],
        facilities: ["pool", "restaurant", "spa"],
        meal_plan: ["breakfast-included"],
      },
      summary: "Beachfront hotel on the Nusa Dua peninsula.",
      description: "Ocean-front rooms, pool, and a quiet lagoon beach.",
      address: "Kawasan Pariwisata Nusa Dua",
      bookingMode: "rental",
      lat: -8.8009,
      lng: 115.2324,
    }),
    biz({
      id: "biz-canggu-scooter",
      placeId: "pl-canggu",
      slug: "canggu-scooter-rental",
      name: "Canggu Scooter Rental",
      categories: ["motorcycle-scooter-rentals"],
      facets: {
        vehicle_type: ["scooter", "motorcycle"],
        rental_type: ["self-drive", "daily", "weekly"],
        transmission: ["automatic"],
        rental_features: ["helmet-included", "insurance-included"],
      },
      summary: "Daily scooter hire in Canggu.",
      description: "Automatic scooters with helmets, delivered in the Canggu area.",
      address: "Jl. Pantai Batu Bolong, Canggu",
      bookingMode: "rental",
      lat: -8.6478,
      lng: 115.1385,
    }),
    biz({
      id: "biz-denpasar-halal",
      placeId: "pl-denpasar",
      slug: "rumah-makan-halal-denpasar",
      name: "Rumah Makan Halal Denpasar",
      categories: ["restaurants"],
      facets: {
        cuisine: ["indonesian"],
        dietary: ["halal"],
        meal: ["lunch", "dinner"],
        dining_service: ["dine-in", "takeaway"],
      },
      summary: "Halal Indonesian restaurant in Denpasar.",
      description: "Certified halal kitchen serving Indonesian plates in the city.",
      address: "Jl. Teuku Umar, Denpasar",
      bookingMode: "none",
      lat: -8.6724,
      lng: 115.2126,
    }),
    biz({
      id: "biz-aceh-mie",
      placeId: "pl-adm-1171",
      slug: "mie-aceh-cak-pon",
      name: "Mie Aceh Cak Pon",
      categories: ["warungs-local-food"],
      summary: "Warung specializing in spiced Aceh-style noodles.",
      description: "Neighborhood warung serving mie Aceh with beef, seafood, or goat, plus sanger coffee.",
      bookingMode: "none",
      lat: -5.5483,
      lng: 95.3238,
    }),
    biz({
      id: "biz-medan-bika",
      placeId: "pl-medan",
      slug: "bika-ambon-sultan",
      name: "Bika Ambon Sultan",
      categories: ["bakeries-cake-shops"],
      summary: "Bakery known for Medan's signature honeycomb cake.",
      description: "Bakery producing fresh bika ambon and other Medan snacks for pickup or shipping.",
      bookingMode: "none",
      lat: 3.5952,
      lng: 98.6722,
    }),
    biz({
      id: "biz-padang-rm",
      placeId: "pl-adm-1371",
      slug: "nasi-padang-uda-pian",
      name: "Nasi Padang Uda Pian",
      categories: ["restaurants"],
      summary: "Rumah makan serving classic Minang rendang and gulai.",
      description: "Padang-style restaurant with a full display of Minang dishes served rice-first.",
      bookingMode: "none",
      lat: -0.9492,
      lng: 100.3543,
    }),
    biz({
      id: "biz-pekanbaru-gulai",
      placeId: "pl-adm-1471",
      slug: "gulai-ikan-patin-riau",
      name: "Gulai Ikan Patin Riau",
      categories: ["restaurants"],
      summary: "Riau-Malay restaurant known for patin fish curry.",
      description: "Family restaurant serving Riau-Malay river fish curry and grilled specialties.",
      bookingMode: "none",
      lat: 0.5071,
      lng: 101.4478,
    }),
    biz({
      id: "biz-jambi-kopi",
      placeId: "pl-adm-1571",
      slug: "kopi-tempoyak-jambi",
      name: "Kopi Tempoyak Jambi",
      categories: ["cafes-coffee-shops"],
      summary: "Café pairing local coffee with Jambi snacks.",
      description: "Casual café serving Jambi-grown coffee alongside local durian-based snacks.",
      bookingMode: "none",
      lat: -1.6101,
      lng: 103.6131,
    }),
    biz({
      id: "biz-palembang-pempek",
      placeId: "pl-adm-1671",
      slug: "pempek-cek-mek",
      name: "Pempek Cek Mek",
      categories: ["food-stalls-street-food"],
      summary: "Street stall for Palembang's fish-and-sago pempek.",
      description: "Pempek stall serving kapal selam, lenjer, and cuko sauce to order.",
      bookingMode: "none",
      lat: -2.9761,
      lng: 104.7754,
    }),
    biz({
      id: "biz-bengkulu-pindang",
      placeId: "pl-adm-1771",
      slug: "warung-pindang-bengkulu",
      name: "Warung Pindang Bengkulu",
      categories: ["warungs-local-food"],
      summary: "Warung for Bengkulu-style tangy fish pindang.",
      description: "Local warung serving pindang fish soup and coastal Bengkulu dishes.",
      bookingMode: "none",
      lat: -3.7928,
      lng: 102.2608,
    }),
    biz({
      id: "biz-lampung-kopi",
      placeId: "pl-adm-1871",
      slug: "kopi-lampung-robusta-house",
      name: "Kopi Lampung Robusta House",
      categories: ["cafes-coffee-shops"],
      summary: "Café built around Lampung's robusta coffee.",
      description: "Coffee house roasting and brewing Lampung robusta, with light food.",
      bookingMode: "none",
      lat: -5.3971,
      lng: 105.2668,
    }),
    biz({
      id: "biz-babel-mie",
      placeId: "pl-adm-1971",
      slug: "mie-bangka-along",
      name: "Mie Bangka Along",
      categories: ["food-stalls-street-food"],
      summary: "Stall serving Bangka-style noodles.",
      description: "Long-running stall for mie Bangka with pork or seafood toppings.",
      bookingMode: "none",
      lat: -2.1316,
      lng: 106.1169,
    }),
    biz({
      id: "biz-batam-seafood",
      placeId: "pl-adm-2171",
      slug: "seafood-nagoya-batam",
      name: "Seafood Nagoya Batam",
      categories: ["seafood-restaurants"],
      summary: "Seafood restaurant near Nagoya, Batam.",
      description: "Pick-your-own seafood restaurant with Singapore-strait catch.",
      bookingMode: "none",
      lat: 1.0456,
      lng: 104.0305,
    }),
    biz({
      id: "biz-jaksel-cowork",
      placeId: "pl-adm-3171",
      slug: "selatan-coworking-jakarta",
      name: "Selatan Coworking Jakarta",
      categories: ["coworking-spaces"],
      summary: "Coworking space in South Jakarta.",
      description: "Flexible desks and meeting rooms for Jakarta freelancers and startups.",
      bookingMode: "none",
      lat: -6.2615,
      lng: 106.8106,
    }),
    biz({
      id: "biz-bandung-kopi",
      placeId: "pl-bandung",
      slug: "kopi-progo-bandung",
      name: "Kopi Progo Bandung",
      categories: ["cafes-coffee-shops"],
      summary: "Highland-coffee café in central Bandung.",
      description: "Cozy café serving West Java single-origin coffee and pastries.",
      bookingMode: "none",
      lat: -6.9024,
      lng: 107.6106,
    }),
    biz({
      id: "biz-semarang-lumpia",
      placeId: "pl-adm-3374",
      slug: "lumpia-mbak-tutik",
      name: "Lumpia Mbak Tutik",
      categories: ["food-stalls-street-food"],
      summary: "Stall for Semarang's signature spring rolls.",
      description: "Fresh and fried lumpia Semarang with bamboo shoot and egg filling.",
      bookingMode: "none",
      lat: -6.9667,
      lng: 110.4167,
    }),
    biz({
      id: "biz-surabaya-rawon",
      placeId: "pl-surabaya",
      slug: "rawon-kalimas",
      name: "Rawon Kalimas",
      categories: ["restaurants"],
      summary: "Restaurant serving Surabaya's black beef soup.",
      description: "Rawon, rujak cingur, and other East Java classics.",
      bookingMode: "none",
      lat: -7.2575,
      lng: 112.7521,
    }),
    biz({
      id: "biz-serang-sate",
      placeId: "pl-adm-3673",
      slug: "sate-bandeng-serang",
      name: "Sate Bandeng Serang",
      categories: ["warungs-local-food"],
      summary: "Warung for Banten's boneless milkfish satay.",
      description: "Traditional sate bandeng, a Banten specialty, grilled to order.",
      bookingMode: "none",
      lat: -6.1149,
      lng: 106.1503,
    }),
    biz({
      id: "biz-kupang-sei",
      placeId: "pl-adm-5371",
      slug: "sei-sapi-kupang",
      name: "Se'i Sapi Kupang",
      categories: ["restaurants"],
      summary: "Restaurant for Kupang's smoked beef se'i.",
      description: "Smoked beef and pork se'i served with sambal lu'at.",
      bookingMode: "none",
      lat: -10.1772,
      lng: 123.607,
    }),
    biz({
      id: "biz-pontianak-choipan",
      placeId: "pl-adm-6171",
      slug: "choi-pan-pontianak",
      name: "Choi Pan Pontianak",
      categories: ["food-stalls-street-food"],
      summary: "Stall for Pontianak's steamed chive dumplings.",
      description: "Hakka-influenced choi pan and other Pontianak Chinese-Malay snacks.",
      bookingMode: "none",
      lat: -0.0263,
      lng: 109.3425,
    }),
    biz({
      id: "biz-palangkaraya-tour",
      placeId: "pl-adm-6271",
      slug: "susur-sungai-kahayan",
      name: "Susur Sungai Kahayan",
      categories: ["tour-operators-local-guides"],
      summary: "River-tour operator on the Kahayan River.",
      description: "Klotok boat tours along the Kahayan, including orangutan-area day trips.",
      bookingMode: "none",
      lat: -2.2096,
      lng: 113.9213,
    }),
    biz({
      id: "biz-banjarmasin-tour",
      placeId: "pl-adm-6371",
      slug: "susur-pasar-terapung-banjarmasin",
      name: "Susur Pasar Terapung Banjarmasin",
      categories: ["tour-operators-local-guides"],
      summary: "Early-morning floating-market boat tours.",
      description: "Klotok tours of Banjarmasin's floating markets and river canals.",
      bookingMode: "none",
      lat: -3.3186,
      lng: 114.5944,
    }),
    biz({
      id: "biz-balikpapan-kepiting",
      placeId: "pl-adm-6471",
      slug: "kepiting-kenari-balikpapan",
      name: "Kepiting Kenari Balikpapan",
      categories: ["seafood-restaurants"],
      summary: "Seafood restaurant known for Kenari-style crab.",
      description: "Balikpapan seafood house specializing in mud crab and prawns.",
      bookingMode: "none",
      lat: -1.2379,
      lng: 116.8529,
    }),
    biz({
      id: "biz-tarakan-ikan",
      placeId: "pl-adm-6571",
      slug: "ikan-bakar-tarakan",
      name: "Ikan Bakar Tarakan",
      categories: ["seafood-restaurants"],
      summary: "Waterfront restaurant for grilled Tarakan fish.",
      description: "Grilled reef fish and prawns fresh from Tarakan's waters.",
      bookingMode: "none",
      lat: 3.3,
      lng: 117.6333,
    }),
    biz({
      id: "biz-manado-tinutuan",
      placeId: "pl-adm-7171",
      slug: "tinutuan-manado-pagi",
      name: "Tinutuan Manado Pagi",
      categories: ["restaurants"],
      summary: "Breakfast spot for Manado porridge and spicy sides.",
      description: "Morning tinutuan porridge with dabu-dabu and grilled sides.",
      bookingMode: "none",
      lat: 1.4748,
      lng: 124.8421,
    }),
    biz({
      id: "biz-palu-kopi",
      placeId: "pl-adm-7271",
      slug: "kopi-kaili-palu",
      name: "Kopi Kaili Palu",
      categories: ["cafes-coffee-shops"],
      summary: "Café serving Central Sulawesi coffee.",
      description: "Kaili-region coffee and light meals in central Palu.",
      bookingMode: "none",
      lat: -0.8917,
      lng: 119.8707,
    }),
    biz({
      id: "biz-kendari-sate",
      placeId: "pl-adm-7471",
      slug: "sate-gogos-pulo-kendari",
      name: "Sate Gogos Pulo Kendari",
      categories: ["seafood-restaurants"],
      summary: "Seafood spot for Kendari-style grilled fish skewers.",
      description: "Sate gogos and other Southeast Sulawesi coastal grills.",
      bookingMode: "none",
      lat: -3.945,
      lng: 122.4989,
    }),
    biz({
      id: "biz-gorontalo-binte",
      placeId: "pl-adm-7571",
      slug: "binte-biluhuta-gorontalo",
      name: "Binte Biluhuta Gorontalo",
      categories: ["restaurants"],
      summary: "Restaurant for Gorontalo's spiced corn-and-fish soup.",
      description: "Binte biluhuta and other Gorontalo specialties.",
      bookingMode: "none",
      lat: 0.5412,
      lng: 123.0595,
    }),
    biz({
      id: "biz-mamuju-kopi",
      placeId: "pl-adm-7604",
      slug: "kopi-mamuju-mandar",
      name: "Kopi Mamuju Mandar",
      categories: ["cafes-coffee-shops"],
      summary: "Café highlighting Mandar-region coffee.",
      description: "West Sulawesi coffee and snacks overlooking Mamuju bay.",
      bookingMode: "none",
      lat: -2.6785,
      lng: 118.888,
    }),
    biz({
      id: "biz-ambon-ikan",
      placeId: "pl-adm-8171",
      slug: "ikan-kuah-pala-ambon",
      name: "Ikan Kuah Pala Ambon",
      categories: ["seafood-restaurants"],
      summary: "Restaurant for Ambon's nutmeg fish soup.",
      description: "Ikan kuah pala and other Maluku seafood dishes.",
      bookingMode: "none",
      lat: -3.6954,
      lng: 128.1814,
    }),
    biz({
      id: "biz-ternate-rempah",
      placeId: "pl-adm-8271",
      slug: "rempah-ternate-heritage-tour",
      name: "Rempah Ternate Heritage Tour",
      categories: ["cultural-experiences"],
      summary: "Guided tour of Ternate's spice-trade heritage.",
      description: "Walking tour covering Ternate's forts and clove-trade history.",
      bookingMode: "none",
      lat: 0.7833,
      lng: 127.3667,
    }),
    biz({
      id: "biz-manokwari-dive",
      placeId: "pl-adm-9105",
      slug: "manokwari-dive-center",
      name: "Manokwari Dive Center",
      categories: ["diving-snorkeling"],
      summary: "Dive operator on Papua's Bird's Head coast.",
      description: "Reef and wreck dives around Manokwari, with PADI courses.",
      bookingMode: "none",
      lat: -0.8615,
      lng: 134.062,
    }),
    biz({
      id: "biz-sorong-dive",
      placeId: "pl-adm-9271",
      slug: "sorong-raja-ampat-dive-gateway",
      name: "Sorong Raja Ampat Dive Gateway",
      categories: ["diving-snorkeling"],
      summary: "Dive operator and Raja Ampat trip planner.",
      description: "Liveaboard and day-trip bookings for Raja Ampat from Sorong.",
      bookingMode: "none",
      lat: -0.8762,
      lng: 131.2558,
    }),
    biz({
      id: "biz-jayapura-papeda",
      placeId: "pl-adm-9471",
      slug: "papeda-ikan-kuah-kuning-jayapura",
      name: "Papeda Ikan Kuah Kuning Jayapura",
      categories: ["restaurants"],
      summary: "Restaurant for Papua's papeda and yellow fish soup.",
      description: "Papeda served with kuah kuning and other Papuan coastal dishes.",
      bookingMode: "none",
      lat: -2.5337,
      lng: 140.7181,
    }),
    biz({
      id: "biz-merauke-budaya",
      placeId: "pl-adm-9501",
      slug: "budaya-marind-merauke-tour",
      name: "Budaya Marind Merauke Tour",
      categories: ["cultural-experiences"],
      summary: "Cultural tour introducing Marind traditions.",
      description: "Guided cultural visits near Merauke covering Marind customs.",
      bookingMode: "none",
      lat: -8.4676,
      lng: 140.3936,
    }),
    biz({
      id: "biz-nabire-dive",
      placeId: "pl-adm-9604",
      slug: "teluk-cenderawasih-dive-nabire",
      name: "Teluk Cenderawasih Dive Nabire",
      categories: ["diving-snorkeling"],
      summary: "Dive operator for Cenderawasih Bay whale sharks.",
      description: "Whale-shark and reef dive trips into Cenderawasih Bay.",
      bookingMode: "none",
      lat: -3.3667,
      lng: 135.4833,
    }),
    biz({
      id: "biz-wamena-baliem",
      placeId: "pl-adm-9702",
      slug: "lembah-baliem-culture-walk",
      name: "Lembah Baliem Culture Walk",
      categories: ["cultural-experiences"],
      summary: "Guided walks through the Baliem Valley.",
      description: "Cultural treks introducing Dani village life in the Baliem Valley.",
      bookingMode: "none",
      lat: -4.0925,
      lng: 138.9375,
    }),
  ];

  const vendors = [
    {
      id: "vnd-celuk",
      businessId: "biz-celuk",
      name: "Celuk Silver Shop",
      slug: "celuk-silver-shop",
      description: "Handmade silver from the Celuk workshop.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-ring",
          name: "Silver Ring",
          slug: "silver-ring",
          price: 250000,
          currency: "IDR",
          stock: 24,
          description: "Handcrafted sterling silver ring.",
        },
        {
          id: "prd-necklace",
          name: "Silver Necklace",
          slug: "silver-necklace",
          price: 450000,
          currency: "IDR",
          stock: 12,
          description: "Traditional Celuk necklace.",
        },
      ],
    },
    {
      id: "vnd-batik",
      businessId: "biz-batik-g",
      name: "Gianyar Batik Store",
      slug: "gianyar-batik-store",
      description: "Batik cloth and ready-to-wear.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-batik-cloth",
          name: "Batik Cloth",
          slug: "batik-cloth",
          price: 350000,
          currency: "IDR",
          stock: 40,
          description: "Hand-stamped batik fabric.",
        },
      ],
    },
    {
      id: "vnd-malio",
      businessId: "biz-batik-malio",
      name: "Malioboro Batik Store",
      slug: "malioboro-batik-store",
      description: "Yogya batik for visitors.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-shirt",
          name: "Batik Shirt",
          slug: "batik-shirt",
          price: 275000,
          currency: "IDR",
          stock: 30,
          description: "Ready-to-wear batik shirt.",
        },
      ],
    },
  ];

  const reviews = [
    {
      id: "rev-1",
      businessId: "biz-pande-egi",
      authorName: "Maya",
      service: 5,
      value: 5,
      location: 4,
      cleanliness: 4,
      comment: "Best babi guling we found in Gianyar.",
      createdAt: t,
    },
    {
      id: "rev-2",
      businessId: "biz-single-fin",
      authorName: "Tom",
      service: 4,
      value: 3,
      location: 5,
      cleanliness: 4,
      comment: "Unbeatable view after a surf session.",
      createdAt: t,
    },
  ];

  return {
    islands,
    places,
    businesses,
    users,
    claims: [],
    reviews,
    bookings: [],
    vendors,
    invites: [],
    recoveryTokens: [],
    reports: [],
  };
}
