import type { DataStore } from "./types.js";

const now = () => new Date().toISOString();

/** Well-known local demo accounts — never auto-delete matching production users. */
export const DEMO_ACCOUNT_EMAILS = [
  "admin@nusa.business",
  "agent@nusa.business",
  "owner@example.com",
] as const;

/**
 * Geography-only store for production / empty bootstrap.
 * No demo users, businesses, reviews, bookings, or vendors.
 */
export function createReferenceStore(): DataStore {
  const full = createSeed();
  return {
    islands: full.islands,
    places: full.places,
    businesses: [],
    users: [],
    claims: [],
    reviews: [],
    bookings: [],
    vendors: [],
    invites: [],
    recoveryTokens: [],
  };
}

/** Full local/demo catalog (geography + sample listings + demo users). */
export function createSeed(): DataStore {
  const t = now();

  const islands = [
    {
      id: "isl-bali",
      slug: "bali",
      name: "Bali",
      tagline: "Island of the Gods — local businesses for visitors and locals",
      status: "active" as const,
    },
    {
      id: "isl-java",
      slug: "java",
      name: "Java",
      tagline: "Java’s cities, culture, and cuisine",
      status: "active" as const,
    },
    {
      id: "isl-lombok",
      slug: "lombok",
      name: "Lombok",
      tagline: "Gilis, surf, and island life",
      status: "active" as const,
    },
    {
      id: "isl-sumatra",
      slug: "sumatra",
      name: "Sumatra",
      tagline: "From Medan to the highlands",
      status: "active" as const,
    },
    {
      id: "isl-sulawesi",
      slug: "sulawesi",
      name: "Sulawesi",
      tagline: "Makassar, Manado, and beyond",
      status: "active" as const,
    },
    {
      id: "isl-kalimantan",
      slug: "kalimantan",
      name: "Kalimantan",
      tagline: "Borneo’s Indonesian shores",
      status: "coming_soon" as const,
    },
    {
      id: "isl-maluku",
      slug: "maluku",
      name: "Maluku",
      tagline: "Spice islands",
      status: "coming_soon" as const,
    },
    {
      id: "isl-papua",
      slug: "papua",
      name: "Papua",
      tagline: "Eastern frontier",
      status: "coming_soon" as const,
    },
  ];

  const places = [
    {
      id: "pl-badung",
      islandId: "isl-bali",
      slug: "badung",
      name: "Badung",
      type: "kabupaten" as const,
      summary: "South Bali — surf coasts, Canggu, and the Bukit.",
    },
    {
      id: "pl-gianyar",
      islandId: "isl-bali",
      slug: "gianyar",
      name: "Gianyar",
      type: "kabupaten" as const,
      summary: "Cultural heartland — babi guling, silver, batik.",
    },
    {
      id: "pl-denpasar",
      islandId: "isl-bali",
      slug: "denpasar",
      name: "Denpasar",
      type: "kota" as const,
      summary: "Provincial capital and everyday Bali.",
    },
    {
      id: "pl-buleleng",
      islandId: "isl-bali",
      slug: "buleleng",
      name: "Buleleng",
      type: "kabupaten" as const,
      summary: "North-coast Bali — Lovina and black-sand villages.",
    },
    {
      id: "pl-karangasem",
      islandId: "isl-bali",
      slug: "karangasem",
      name: "Karangasem",
      type: "kabupaten" as const,
      summary: "East Bali — Amed, Agung, and traditional villages.",
    },
    {
      id: "pl-uluwatu",
      islandId: "isl-bali",
      slug: "uluwatu",
      name: "Uluwatu",
      type: "tourist_area" as const,
      parentPlaceId: "pl-badung",
      summary: "Cliff temples, surf breaks, and sunset kecak.",
    },
    {
      id: "pl-jimbaran",
      islandId: "isl-bali",
      slug: "jimbaran",
      name: "Jimbaran",
      type: "tourist_area" as const,
      parentPlaceId: "pl-badung",
      summary: "Bay seafood and beach warungs.",
    },
    {
      id: "pl-ubud",
      islandId: "isl-bali",
      slug: "ubud",
      name: "Ubud",
      type: "tourist_area" as const,
      parentPlaceId: "pl-gianyar",
      summary: "Rice terraces, wellness, and arts.",
    },
    {
      id: "pl-canggu",
      islandId: "isl-bali",
      slug: "canggu",
      name: "Canggu",
      type: "tourist_area" as const,
      parentPlaceId: "pl-badung",
      summary: "Surf, cafés, and digital-nomad energy.",
    },
    {
      id: "pl-seminyak",
      islandId: "isl-bali",
      slug: "seminyak",
      name: "Seminyak",
      type: "tourist_area" as const,
      parentPlaceId: "pl-badung",
      summary: "Beach clubs, boutiques, and nightlife.",
    },
    {
      id: "pl-sanur",
      islandId: "isl-bali",
      slug: "sanur",
      name: "Sanur",
      type: "tourist_area" as const,
      parentPlaceId: "pl-denpasar",
      summary: "Quiet east-coast beaches and family stays.",
    },
    {
      id: "pl-kuta",
      islandId: "isl-bali",
      slug: "kuta",
      name: "Kuta",
      type: "tourist_area" as const,
      parentPlaceId: "pl-badung",
      summary: "Classic beach strip and arrivals hub.",
    },
    {
      id: "pl-nusa-dua",
      islandId: "isl-bali",
      slug: "nusa-dua",
      name: "Nusa Dua",
      type: "tourist_area" as const,
      parentPlaceId: "pl-badung",
      summary: "Resort peninsula on the Bukit.",
    },
    {
      id: "pl-lovina",
      islandId: "isl-bali",
      slug: "lovina",
      name: "Lovina",
      type: "tourist_area" as const,
      parentPlaceId: "pl-buleleng",
      summary: "North-coast dolphins and black sand.",
    },
    {
      id: "pl-amed",
      islandId: "isl-bali",
      slug: "amed",
      name: "Amed",
      type: "tourist_area" as const,
      parentPlaceId: "pl-karangasem",
      summary: "Diving villages on the east coast.",
    },
    {
      id: "pl-yogya",
      islandId: "isl-java",
      slug: "yogyakarta",
      name: "Yogyakarta",
      type: "kota" as const,
      summary: "Gudeg, batik, and gateways to Borobudur.",
    },
    {
      id: "pl-bandung",
      islandId: "isl-java",
      slug: "bandung",
      name: "Bandung",
      type: "kota" as const,
      summary: "Cool highlands, coffee, and shopping.",
    },
    {
      id: "pl-jakarta",
      islandId: "isl-java",
      slug: "jakarta",
      name: "Jakarta",
      type: "kota" as const,
      summary: "Capital metro — food, culture, business.",
    },
    {
      id: "pl-surabaya",
      islandId: "isl-java",
      slug: "surabaya",
      name: "Surabaya",
      type: "kota" as const,
      summary: "East Java’s port city and culinary hub.",
    },
    {
      id: "pl-lombok-utara",
      islandId: "isl-lombok",
      slug: "lombok-utara",
      name: "Lombok Utara",
      type: "kabupaten" as const,
      summary: "North Lombok and the Gili islands.",
    },
    {
      id: "pl-lombok-tengah",
      islandId: "isl-lombok",
      slug: "lombok-tengah",
      name: "Lombok Tengah",
      type: "kabupaten" as const,
      summary: "Central Lombok — Kuta and south-coast surf.",
    },
    {
      id: "pl-gili-t",
      islandId: "isl-lombok",
      slug: "gili-trawangan",
      name: "Gili Trawangan",
      type: "tourist_area" as const,
      parentPlaceId: "pl-lombok-utara",
      summary: "Diving, nightlife, and island hopping.",
    },
    {
      id: "pl-kuta-lombok",
      islandId: "isl-lombok",
      slug: "kuta",
      name: "Kuta Lombok",
      type: "tourist_area" as const,
      parentPlaceId: "pl-lombok-tengah",
      summary: "South Lombok surf camps.",
    },
    {
      id: "pl-medan",
      islandId: "isl-sumatra",
      slug: "medan",
      name: "Medan",
      type: "kota" as const,
      summary: "Sumatra’s largest city and food capital.",
    },
    {
      id: "pl-makassar",
      islandId: "isl-sulawesi",
      slug: "makassar",
      name: "Makassar",
      type: "kota" as const,
      summary: "Coto, phinisi, and Sulawesi gateway.",
    },
  ];

  const users = [
    {
      id: "usr-admin",
      email: "admin@nusa.business",
      name: "Nusa Admin",
      role: "admin" as const,
      password: "admin123",
    },
    {
      id: "usr-agent",
      email: "agent@nusa.business",
      name: "Field Agent Bali",
      role: "field_agent" as const,
      password: "agent123",
    },
    {
      id: "usr-owner",
      email: "owner@example.com",
      name: "Listing Owner",
      role: "owner" as const,
      password: "owner123",
    },
  ];

  const biz = (
    partial: Omit<
      DataStore["businesses"][number],
      "gallery" | "openingHours" | "faq" | "createdAt" | "updatedAt" | "status"
    > & { status?: DataStore["businesses"][number]["status"] },
  ) => ({
    gallery: [],
    openingHours: [
      { day: "Mon", open: "09:00", close: "21:00" },
      { day: "Tue", open: "09:00", close: "21:00" },
      { day: "Wed", open: "09:00", close: "21:00" },
      { day: "Thu", open: "09:00", close: "21:00" },
      { day: "Fri", open: "09:00", close: "22:00" },
      { day: "Sat", open: "09:00", close: "22:00" },
      { day: "Sun", open: "10:00", close: "21:00" },
    ],
    faq: [],
    createdAt: t,
    updatedAt: t,
    status: partial.status ?? ("published" as const),
    ...partial,
  });

  const businesses = [
    biz({
      id: "biz-single-fin",
      placeId: "pl-uluwatu",
      slug: "single-fin-uluwatu",
      name: "Single Fin Uluwatu",
      categories: ["Food & Drink", "Sports & Recreation"],
      summary: "Cliffside surf café above Uluwatu.",
      description:
        "Iconic surf hangout with ocean views, cold drinks, and sunset energy.",
      address: "Jl. Pura Luhur Uluwatu, Pecatu",
      phone: "+62 361 0001001",
      bookingMode: "none",
      lat: -8.8291,
      lng: 115.0849,
    }),
    biz({
      id: "biz-kecak",
      placeId: "pl-uluwatu",
      slug: "uluwatu-temple-kecak",
      name: "Uluwatu Temple Kecak",
      categories: ["Tourism & Experiences", "Arts & Culture"],
      summary: "Sunset kecak and fire dance at the temple cliffs.",
      description: "Cultural performance operator for Uluwatu sunset shows.",
      bookingMode: "event",
      lat: -8.8295,
      lng: 115.0845,
    }),
    biz({
      id: "biz-alchemy",
      placeId: "pl-uluwatu",
      slug: "alchemy-uluwatu",
      name: "Alchemy Uluwatu",
      categories: ["Health & Wellness", "Food & Drink"],
      summary: "Plant-based wellness café and juice bar.",
      description: "Cold-pressed juices, bowls, and wellness-minded dining.",
      bookingMode: "service",
      lat: -8.821,
      lng: 115.088,
    }),
    biz({
      id: "biz-menega",
      placeId: "pl-jimbaran",
      slug: "menega-cafe",
      name: "Menega Cafe",
      categories: ["Food & Drink"],
      summary: "Jimbaran beach seafood institution.",
      description: "Grilled seafood on the sand with bay views.",
      bookingMode: "service",
      lat: -8.784,
      lng: 115.163,
    }),
    biz({
      id: "biz-fish-tours",
      placeId: "pl-jimbaran",
      slug: "jimbaran-fish-market-tours",
      name: "Jimbaran Fish Market Tours",
      categories: ["Tourism & Experiences"],
      summary: "Local market and seafood culture tours.",
      description: "Guided morning walks through Jimbaran’s fish market.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-spa-jim",
      placeId: "pl-jimbaran",
      slug: "spa-jimbaran-bay",
      name: "Spa Jimbaran Bay",
      categories: ["Health & Wellness", "Beauty & Personal Care"],
      summary: "Bay-side spa treatments.",
      description: "Massage and spa packages near Jimbaran Bay.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-pande-egi",
      placeId: "pl-gianyar",
      slug: "babi-guling-pande-egi",
      name: "Babi Guling Pande Egi",
      categories: ["Food & Drink"],
      summary: "Iconic Gianyar babi guling.",
      description:
        "Local favourite for Balinese roast pork — a must when visiting Gianyar.",
      address: "Jl. Ngurah Rai 12, Gianyar",
      whatsapp: "+62 812 0000001",
      bookingMode: "none",
      registeredByAgentId: "usr-agent",
      lat: -8.5439,
      lng: 115.325,
    }),
    biz({
      id: "biz-kopi-rai",
      placeId: "pl-gianyar",
      slug: "kopi-ngurah-rai",
      name: "Kopi Ngurah Rai",
      categories: ["Food & Drink"],
      summary: "Neighbour coffee stall in the same ruko row.",
      description: "Espresso and Bali kopi next door to the babi guling counters.",
      address: "Jl. Ngurah Rai 12, Gianyar",
      whatsapp: "+62 812 0000012",
      bookingMode: "none",
      lat: -8.5439,
      lng: 115.325,
    }),
    biz({
      id: "biz-celuk",
      placeId: "pl-gianyar",
      slug: "celuk-silver-workshop",
      name: "Celuk Silver Workshop",
      categories: ["Arts & Culture", "Shopping & Retail"],
      summary: "Traditional silversmith workshop in Celuk.",
      description: "Handcrafted silver jewellery and workshop visits.",
      address: "Jl. Raya Celuk, Gianyar",
      bookingMode: "service",
      vendorId: "vnd-celuk",
      lat: -8.5485,
      lng: 115.318,
    }),
    biz({
      id: "biz-batik-g",
      placeId: "pl-gianyar",
      slug: "batik-gianyar-gallery",
      name: "Batik Gianyar Gallery",
      categories: ["Arts & Culture", "Shopping & Retail"],
      summary: "Batik textiles and gallery.",
      description: "Local batik makers and showroom in Gianyar.",
      address: "Jl. Dharma Giri, Gianyar",
      bookingMode: "none",
      vendorId: "vnd-batik",
      lat: -8.5412,
      lng: 115.331,
    }),
    biz({
      id: "biz-warung-pasar",
      placeId: "pl-gianyar",
      slug: "warung-pasar-gianyar",
      name: "Warung Pasar Gianyar",
      categories: ["Food & Drink"],
      summary: "Market warung for local lunch plates.",
      description: "Simple nasi campur and sayur within walking distance of the centre.",
      address: "Pasar Gianyar",
      bookingMode: "none",
      lat: -8.5455,
      lng: 115.3275,
    }),
    biz({
      id: "biz-bpr-gianyar",
      placeId: "pl-gianyar",
      slug: "bpr-gianyar-pusat",
      name: "BPR Gianyar Pusat",
      categories: ["Professional Services"],
      summary: "Local bank branch for everyday banking.",
      description: "Community bank counter near Gianyar town centre.",
      address: "Jl. Ngurah Rai 40, Gianyar",
      bookingMode: "none",
      lat: -8.5448,
      lng: 115.3262,
    }),
    biz({
      id: "biz-klinik-g",
      placeId: "pl-gianyar",
      slug: "klinik-sehat-gianyar",
      name: "Klinik Sehat Gianyar",
      categories: ["Health & Wellness"],
      summary: "Neighbourhood clinic and apotek counter.",
      description: "General practice and basic pharmacy services.",
      address: "Jl. Bypass Dharma Giri",
      bookingMode: "service",
      lat: -8.54,
      lng: 115.329,
    }),
    biz({
      id: "biz-ibu-oka",
      placeId: "pl-ubud",
      slug: "warung-babi-guling-ibu-oka",
      name: "Warung Babi Guling Ibu Oka",
      categories: ["Food & Drink"],
      summary: "Famous Ubud babi guling warung.",
      description: "Classic Balinese roast pork in central Ubud.",
      address: "Jalan Suweta, Ubud",
      bookingMode: "none",
      lat: -8.5069,
      lng: 115.2625,
    }),
    biz({
      id: "biz-yoga-barn",
      placeId: "pl-ubud",
      slug: "yoga-barn-ubud",
      name: "Yoga Barn Ubud",
      categories: ["Health & Wellness"],
      summary: "Wellness classes and yoga community hub.",
      description: "Drop-in classes, workshops, and wellness events.",
      address: "Pengosekan, Ubud",
      bookingMode: "service",
      lat: -8.5195,
      lng: 115.265,
    }),
    biz({
      id: "biz-monkey-cafe",
      placeId: "pl-ubud",
      slug: "sacred-monkey-forest-cafe",
      name: "Sacred Monkey Forest Cafe",
      categories: ["Food & Drink"],
      summary: "Café near the monkey forest sanctuary.",
      description: "Casual café for visitors exploring the sanctuary.",
      bookingMode: "none",
      lat: -8.5188,
      lng: 115.2594,
    }),
    biz({
      id: "biz-old-mans",
      placeId: "pl-canggu",
      slug: "old-mans-canggu",
      name: "Old Man's Canggu",
      categories: ["Food & Drink", "Sports & Recreation"],
      summary: "Beachside F&B and surf culture.",
      description: "Canggu beach hangout with food, drinks, and sunset vibes.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-surf-canggu",
      placeId: "pl-canggu",
      slug: "canggu-surf-school",
      name: "Canggu Surf School",
      categories: ["Sports & Recreation", "Tourism & Experiences"],
      summary: "Surf lessons for all levels.",
      description: "Board rental and lessons on Canggu breaks.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-cowork",
      placeId: "pl-canggu",
      slug: "digital-nomad-cowork-canggu",
      name: "Digital Nomad Cowork Canggu",
      categories: ["Professional Services"],
      summary: "Coworking for remote workers.",
      description: "Desks, wifi, and community events in Canggu.",
      bookingMode: "rental",
    }),
    biz({
      id: "biz-gudeg",
      placeId: "pl-yogya",
      slug: "gudeg-yu-djum",
      name: "Gudeg Yu Djum",
      categories: ["Food & Drink"],
      summary: "Classic Yogyakarta gudeg.",
      description: "Legendary jackfruit stew institution.",
      bookingMode: "none",
    }),
    biz({
      id: "biz-batik-malio",
      placeId: "pl-yogya",
      slug: "batik-malioboro-house",
      name: "Batik Malioboro House",
      categories: ["Shopping & Retail", "Arts & Culture"],
      summary: "Batik near Malioboro.",
      description: "Retail batik and textiles in Yogyakarta.",
      bookingMode: "none",
      vendorId: "vnd-malio",
    }),
    biz({
      id: "biz-boro",
      placeId: "pl-yogya",
      slug: "borobudur-sunrise-tours",
      name: "Borobudur Sunrise Tours",
      categories: ["Tourism & Experiences"],
      summary: "Sunrise temple tours from Yogyakarta.",
      description: "Guided early-morning Borobudur experiences.",
      bookingMode: "event",
    }),
    biz({
      id: "biz-scuba",
      placeId: "pl-gili-t",
      slug: "scuba-republic-gili",
      name: "Scuba Republic Gili",
      categories: ["Sports & Recreation", "Tourism & Experiences"],
      summary: "Diving centre on Gili Trawangan.",
      description: "Fun dives and courses around the Gilis.",
      bookingMode: "service",
    }),
    biz({
      id: "biz-coto",
      placeId: "pl-makassar",
      slug: "coto-makassar-warung",
      name: "Coto Makassar Warung",
      categories: ["Food & Drink"],
      summary: "Traditional Makassar coto.",
      description: "Local beef stew warung favourites.",
      bookingMode: "none",
    }),
  ];

  const vendors = [
    {
      id: "vnd-celuk",
      businessId: "biz-celuk",
      name: "Celuk Silver Shop",
      slug: "celuk-silver-shop",
      description: "Handmade silver from the Celuk workshop.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-ring",
          name: "Silver Ring",
          slug: "silver-ring",
          price: 250000,
          currency: "IDR",
          stock: 24,
          description: "Handcrafted sterling silver ring.",
        },
        {
          id: "prd-necklace",
          name: "Silver Necklace",
          slug: "silver-necklace",
          price: 450000,
          currency: "IDR",
          stock: 12,
          description: "Traditional Celuk necklace.",
        },
      ],
    },
    {
      id: "vnd-batik",
      businessId: "biz-batik-g",
      name: "Gianyar Batik Store",
      slug: "gianyar-batik-store",
      description: "Batik cloth and ready-to-wear.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-batik-cloth",
          name: "Batik Cloth",
          slug: "batik-cloth",
          price: 350000,
          currency: "IDR",
          stock: 40,
          description: "Hand-stamped batik fabric.",
        },
      ],
    },
    {
      id: "vnd-malio",
      businessId: "biz-batik-malio",
      name: "Malioboro Batik Store",
      slug: "malioboro-batik-store",
      description: "Yogya batik for visitors.",
      commissionPercent: 0,
      createdAt: t,
      products: [
        {
          id: "prd-shirt",
          name: "Batik Shirt",
          slug: "batik-shirt",
          price: 275000,
          currency: "IDR",
          stock: 30,
          description: "Ready-to-wear batik shirt.",
        },
      ],
    },
  ];

  const reviews = [
    {
      id: "rev-1",
      businessId: "biz-pande-egi",
      authorName: "Maya",
      service: 5,
      value: 5,
      location: 4,
      cleanliness: 4,
      comment: "Best babi guling we found in Gianyar.",
      createdAt: t,
    },
    {
      id: "rev-2",
      businessId: "biz-single-fin",
      authorName: "Tom",
      service: 4,
      value: 3,
      location: 5,
      cleanliness: 4,
      comment: "Unbeatable view after a surf session.",
      createdAt: t,
    },
  ];

  return {
    islands,
    places,
    businesses,
    users,
    claims: [],
    reviews,
    bookings: [],
    vendors,
    invites: [],
    recoveryTokens: [],
  };
}
