/**
 * Indonesian labels for directory facet keys and values.
 * English `label` on FacetDef stays canonical for slugs.
 */
export const FACET_KEY_LABELS_ID: Record<string, string> = {
  "accessibility": "Aksesibilitas",
  "accreditation": "Akreditasi",
  "activity": "Aktivitas",
  "age_group": "Kelompok usia",
  "alcohol": "Alkohol",
  "amenities": "Fasilitas",
  "animal": "Hewan",
  "appointment": "Janji",
  "audience": "Audiens",
  "availability": "Ketersediaan",
  "bedrooms": "Kamar tidur",
  "boarding_type": "Jenis penitipan",
  "booking": "Pemesanan",
  "brand": "Merek",
  "building_area": "Luas bangunan",
  "business_features": "Fitur bisnis",
  "business_service": "Layanan bisnis",
  "business_services": "Layanan bisnis",
  "care_mode": "Cara perawatan",
  "certification": "Sertifikasi",
  "client_type": "Jenis klien",
  "company_stage": "Tahap perusahaan",
  "construction_stage": "Tahap konstruksi",
  "coverage": "Cakupan",
  "credentials": "Kredensial",
  "cuisine": "Masakan",
  "currency": "Mata uang",
  "curriculum": "Kurikulum",
  "customer_type": "Jenis pelanggan",
  "deliverable": "Hasil kerja",
  "delivery": "Pengiriman",
  "destination_service": "Layanan destinasi",
  "development": "Pengembangan",
  "device": "Perangkat",
  "diagnostics": "Diagnostik",
  "dietary": "Diet",
  "difficulty": "Tingkat kesulitan",
  "dining_service": "Layanan makan",
  "distance": "Jarak",
  "duration": "Durasi",
  "eco_options": "Opsi ramah lingkungan",
  "education_level": "Jenjang pendidikan",
  "emergency": "Darurat",
  "engagement": "Keterlibatan",
  "entertainment": "Hiburan",
  "equipment": "Peralatan",
  "event_size": "Ukuran acara",
  "event_type": "Jenis acara",
  "facilities": "Fasilitas",
  "facility": "Fasilitas",
  "features": "Fitur",
  "financial_product": "Produk keuangan",
  "fitness_type": "Jenis kebugaran",
  "food_type": "Jenis makanan",
  "format": "Format",
  "frequency": "Frekuensi",
  "fuel_type": "Jenis bahan bakar",
  "hours": "Jam",
  "included": "Termasuk",
  "industry": "Industri",
  "insurance": "Asuransi",
  "land_area": "Luas tanah",
  "language_of_instruction": "Bahasa pengantar",
  "languages": "Bahasa",
  "legal_specialty": "Spesialisasi hukum",
  "licensing": "Perizinan",
  "location": "Lokasi",
  "location_feature": "Fitur lokasi",
  "materials": "Bahan",
  "meal": "Waktu makan",
  "meal_plan": "Paket makan",
  "membership": "Keanggotaan",
  "nightly_price": "Harga per malam",
  "origin": "Asal",
  "package": "Paket",
  "parking": "Parkir",
  "parts": "Suku cadang",
  "patient_type": "Jenis pasien",
  "payments": "Pembayaran",
  "pet_size": "Ukuran hewan",
  "pickup": "Penjemputan",
  "planning_level": "Tingkat perencanaan",
  "policies": "Kebijakan",
  "practitioner": "Praktisi",
  "price_level": "Tingkat harga",
  "pricing": "Harga",
  "product_type": "Jenis produk",
  "production": "Produksi",
  "professional_type": "Jenis profesional",
  "project_type": "Jenis proyek",
  "promotions": "Promo",
  "property_features": "Fitur properti",
  "property_type": "Jenis properti",
  "protection": "Perlindungan",
  "provider_preference": "Preferensi penyedia",
  "rating": "Rating",
  "rental_features": "Fitur sewa",
  "rental_type": "Jenis sewa",
  "repair_service": "Layanan servis",
  "requirements": "Persyaratan",
  "response": "Respons",
  "response_time": "Waktu respons",
  "returns": "Pengembalian",
  "room_type": "Jenis kamar",
  "schedule": "Jadwal",
  "service": "Layanan",
  "service_mode": "Mode layanan",
  "session_type": "Jenis sesi",
  "setting": "Suasana",
  "shipment": "Kiriman",
  "shopping_mode": "Cara belanja",
  "skill_level": "Tingkat keahlian",
  "special_handling": "Penanganan khusus",
  "specialization": "Spesialisasi",
  "specialty": "Spesialisasi",
  "speed": "Kecepatan",
  "star_rating": "Bintang",
  "stay_features": "Fitur menginap",
  "style": "Gaya",
  "subject": "Subjek",
  "support": "Dukungan",
  "support_type": "Jenis dukungan",
  "sustainability": "Keberlanjutan",
  "transaction": "Transaksi",
  "transmission": "Transmisi",
  "transport": "Transportasi",
  "transport_route": "Rute",
  "treatment_style": "Gaya perawatan",
  "turnaround": "Waktu pengerjaan",
  "urgency": "Urgensi",
  "vehicle_type": "Jenis kendaraan",
  "verification": "Verifikasi",
  "veterinary_specialty": "Spesialisasi hewan",
  "warranty": "Garansi",
  "weight": "Berat",
  "workshop_type": "Jenis bengkel",
};

/** Keyed as `{facetKey}::{valueSlug}`. */
export const FACET_VALUE_LABELS_ID: Record<string, string> = {
  "accessibility::accessible-parking": "Parkir aksesibel",
  "accessibility::accessible-toilet": "Toilet aksesibel",
  "accessibility::wheelchair-entrance": "Akses kursi roda",
  "accreditation::certified-training": "Pelatihan bersertifikat",
  "accreditation::government-accredited": "Terakreditasi pemerintah",
  "accreditation::internationally-accredited": "Terakreditasi internasional",
  "activity::adventure": "Petualangan",
  "activity::boating": "Perahu",
  "activity::cultural": "Budaya",
  "activity::diving": "Diving",
  "activity::hiking": "Hiking",
  "activity::snorkeling": "Snorkling",
  "activity::surfing": "Selancar",
  "activity::wellness": "Wellness",
  "age_group::adults": "Dewasa",
  "age_group::children": "Anak-anak",
  "age_group::infants": "Bayi",
  "age_group::teenagers": "Remaja",
  "age_group::toddlers": "Balita",
  "alcohol::beer-and-wine": "Bir dan anggur",
  "alcohol::cocktails": "Koktail",
  "alcohol::full-bar": "Bar lengkap",
  "alcohol::no-alcohol": "Tanpa alkohol",
  "amenities::air-conditioning": "AC",
  "amenities::prayer-room": "Mushola",
  "amenities::toilet": "Toilet",
  "amenities::waiting-area": "Ruang tunggu",
  "amenities::wi-fi": "Wi-Fi",
  "animal::bird": "Burung",
  "animal::cat": "Kucing",
  "animal::dog": "Anjing",
  "animal::exotic-animal": "Hewan eksotis",
  "animal::livestock": "Ternak",
  "animal::reptile": "Reptil",
  "appointment::appointment": "Janji",
  "appointment::consultation": "Konsultasi",
  "appointment::online-consultation": "Konsultasi daring",
  "appointment::same-day": "Hari yang sama",
  "appointment::walk-in": "Tanpa janji",
  "audience::child-friendly": "Ramah anak",
  "audience::children": "Anak-anak",
  "audience::corporate-groups": "Grup perusahaan",
  "audience::couples": "Pasangan",
  "audience::families": "Keluarga",
  "audience::family-friendly": "Ramah keluarga",
  "audience::men": "Pria",
  "audience::pet-friendly": "Ramah hewan",
  "audience::seniors": "Lansia",
  "audience::unisex": "Unisex",
  "audience::women": "Perempuan",
  "audience::women-friendly": "Ramah perempuan",
  "availability::24-hour-atm": "ATM 24 jam",
  "availability::24-hours": "24 jam",
  "availability::appointment": "Janji",
  "availability::emergency-24-hour": "Darurat 24 jam",
  "availability::emergency-legal-support": "Dukungan hukum darurat",
  "availability::open-late": "Buka malam",
  "availability::open-now": "Buka sekarang",
  "availability::public-holidays": "Hari libur",
  "availability::walk-in": "Tanpa janji",
  "availability::weekend-service": "Layanan akhir pekan",
  "availability::weekends": "Akhir pekan",
  "bedrooms::1": "1",
  "bedrooms::2": "2",
  "bedrooms::3": "3",
  "bedrooms::4-plus": "4+",
  "bedrooms::studio": "Studio",
  "boarding_type::cage-free": "Tanpa kandang",
  "boarding_type::long-term": "Jangka panjang",
  "boarding_type::private-room": "Kamar privat",
  "boarding_type::shared": "Bersama",
  "booking::appointment": "Janji",
  "booking::appointment-required": "Wajib janji",
  "booking::free-cancellation": "Batal gratis",
  "booking::instant-confirmation": "Konfirmasi instan",
  "booking::online-booking": "Pesan daring",
  "booking::same-day-booking": "Pesan hari ini",
  "booking::walk-in": "Tanpa janji",
  "booking::walk-ins": "Tanpa janji",
  "brand::acer": "Acer",
  "brand::apple": "Apple",
  "brand::asus": "Asus",
  "brand::lenovo": "Lenovo",
  "brand::oppo": "Oppo",
  "brand::other": "Lainnya",
  "brand::samsung": "Samsung",
  "brand::vivo": "Vivo",
  "brand::xiaomi": "Xiaomi",
  "building_area::150-plus-m2": "150 m²+",
  "building_area::50-150m2": "50–150 m²",
  "building_area::under-50m2": "Di bawah 50 m²",
  "business_features::locally-owned": "Milik lokal",
  "business_features::plastic-free": "Tanpa plastik",
  "business_features::sustainable": "Berkelanjutan",
  "business_features::women-owned": "Milik perempuan",
  "business_service::cloud-services": "Layanan cloud",
  "business_service::cybersecurity": "Keamanan siber",
  "business_service::it-support": "Dukungan IT",
  "business_service::networking": "Jaringan",
  "business_services::fulfillment": "Fulfillment",
  "business_services::inventory-management": "Manajemen stok",
  "business_services::packing": "Pengepakan",
  "business_services::warehousing": "Pergudangan",
  "care_mode::emergency": "Darurat",
  "care_mode::home-visit": "Kunjungan rumah",
  "care_mode::in-clinic": "Di klinik",
  "care_mode::telemedicine": "Telemedicine",
  "certification::accredited-facility": "Fasilitas terakreditasi",
  "certification::first-aid-certified": "Bersertifikat P3K",
  "certification::licensed-guide": "Pemandu berizin",
  "certification::licensed-practitioner": "Praktisi berizin",
  "certification::padi": "PADI",
  "certification::ssi": "SSI",
  "client_type::corporation": "Perusahaan",
  "client_type::enterprise": "Perusahaan besar",
  "client_type::family": "Keluarga",
  "client_type::foreign-investor": "Investor asing",
  "client_type::individual": "Perorangan",
  "client_type::local-business": "Bisnis lokal",
  "client_type::nonprofit": "Nirlaba",
  "client_type::sme": "UMKM",
  "client_type::startup": "Startup",
  "company_stage::established-business": "Bisnis mapan",
  "company_stage::growing-business": "Bisnis berkembang",
  "company_stage::new-business": "Bisnis baru",
  "construction_stage::building": "Bangunan",
  "construction_stage::completed": "Selesai",
  "construction_stage::design": "Desain",
  "construction_stage::planning": "Perencanaan",
  "construction_stage::renovation": "Renovasi",
  "coverage::inter-island": "Antar-pulau",
  "coverage::international": "Internasional",
  "coverage::local": "Lokal",
  "coverage::nationwide": "Nasional",
  "credentials::association-member": "Anggota asosiasi",
  "credentials::certified": "Bersertifikat",
  "credentials::certified-trainer": "Pelatih bersertifikat",
  "credentials::insured": "Diasuransikan",
  "credentials::licensed": "Berizin",
  "credentials::licensed-advocate": "Advokat berizin",
  "credentials::licensed-veterinarian": "Dokter hewan berizin",
  "credentials::notary": "Notaris",
  "credentials::ppat": "PPAT",
  "credentials::registered-rescue": "Penyelamatan terdaftar",
  "credentials::regulated-financial-provider": "Penyedia keuangan teregulasi",
  "cuisine::asian": "Asia",
  "cuisine::balinese": "Bali",
  "cuisine::chinese": "Tionghoa",
  "cuisine::fusion": "Fusion",
  "cuisine::indian": "India",
  "cuisine::indonesian": "Indonesia",
  "cuisine::italian": "Italia",
  "cuisine::japanese": "Jepang",
  "cuisine::javanese": "Jawa",
  "cuisine::mexican": "Meksiko",
  "cuisine::middle-eastern": "Timur Tengah",
  "cuisine::western": "Barat",
  "currency::aud": "AUD",
  "currency::eur": "EUR",
  "currency::idr": "IDR",
  "currency::other": "Lainnya",
  "currency::sgd": "SGD",
  "currency::usd": "USD",
  "curriculum::cambridge": "Cambridge",
  "curriculum::ib": "IB",
  "curriculum::indonesian": "Indonesia",
  "curriculum::international": "Internasional",
  "curriculum::montessori": "Montessori",
  "customer_type::retail": "Ritel",
  "customer_type::trade": "Grosir khusus",
  "customer_type::wholesale": "Grosir",
  "deliverable::digital-files": "File digital",
  "deliverable::edited-video": "Video suntingan",
  "deliverable::prints": "Cetakan",
  "deliverable::raw-footage": "Rekaman mentah",
  "deliverable::social-media-content": "Konten media sosial",
  "delivery::hybrid": "Hibrida",
  "delivery::international-shipping": "Pengiriman internasional",
  "delivery::local-delivery": "Pengiriman lokal",
  "delivery::nationwide-delivery": "Pengiriman nasional",
  "delivery::on-site": "Di lokasi",
  "delivery::remote": "Jarak jauh",
  "destination_service::destination-weddings": "Pernikahan destinasi",
  "destination_service::international-clients": "Klien internasional",
  "destination_service::local-events": "Acara lokal",
  "development::custom-software": "Perangkat lunak kustom",
  "development::e-commerce": "E-commerce",
  "development::mobile-app": "Aplikasi seluler",
  "development::website": "Situs",
  "device::camera": "Kamera",
  "device::desktop": "Desktop",
  "device::laptop": "Laptop",
  "device::networking-equipment": "Peralatan jaringan",
  "device::smartphone": "HP",
  "device::tablet": "Tablet",
  "device::television": "Televisi",
  "diagnostics::laboratory": "Laboratorium",
  "diagnostics::medical-checkup": "Medical checkup",
  "diagnostics::ultrasound": "USG",
  "diagnostics::x-ray": "Rontgen",
  "dietary::dairy-free": "Tanpa susu",
  "dietary::gluten-free": "Tanpa gluten",
  "dietary::halal": "Halal",
  "dietary::organic": "Organik",
  "dietary::vegan": "Vegan",
  "dietary::vegetarian": "Vegetarian",
  "difficulty::challenging": "Menantang",
  "difficulty::easy": "Mudah",
  "difficulty::expert": "Ahli",
  "difficulty::moderate": "Sedang",
  "dining_service::buffet": "Prasmanan",
  "dining_service::delivery": "Pengiriman",
  "dining_service::dine-in": "Makan di tempat",
  "dining_service::reservations": "Reservasi",
  "dining_service::takeaway": "Bungkus",
  "distance::10km": "Dalam 10 km",
  "distance::1km": "Dalam 1 km",
  "distance::25km": "Dalam 25 km",
  "distance::50km": "Dalam 50 km",
  "distance::5km": "Dalam 5 km",
  "duration::full-day": "Seharian",
  "duration::half-day": "Setengah hari",
  "duration::multi-day": "Beberapa hari",
  "duration::under-2-hours": "Di bawah 2 jam",
  "eco_options::eco-friendly-cleaning": "Pembersihan ramah lingkungan",
  "eco_options::non-toxic-products": "Produk non-toksik",
  "eco_options::waste-recycling": "Daur ulang sampah",
  "education_level::adult-learning": "Pembelajaran dewasa",
  "education_level::preschool": "PAUD",
  "education_level::primary": "SD",
  "education_level::secondary": "Sekolah menengah",
  "education_level::university": "Universitas",
  "education_level::vocational": "Kejuruan",
  "emergency::after-hours-it-support": "Dukungan IT di luar jam",
  "emergency::urgent-data-recovery": "Pemulihan data mendesak",
  "engagement::monthly-retainer": "Retainer bulanan",
  "engagement::one-time": "Sekali",
  "engagement::outsourced": "Alih daya",
  "engagement::project-based": "Berbasis proyek",
  "entertainment::dj": "DJ",
  "entertainment::live-band": "Band live",
  "entertainment::mc": "MC",
  "entertainment::traditional-performance": "Pertunjukan tradisional",
  "equipment::audio-recording": "Rekaman audio",
  "equipment::drone": "Drone",
  "equipment::studio-lighting": "Pencahayaan studio",
  "equipment::underwater-camera": "Kamera bawah air",
  "event_size::101-250": "101–250",
  "event_size::25-50": "25–50",
  "event_size::250-plus": "250+",
  "event_size::51-100": "51–100",
  "event_size::under-25": "Di bawah 25",
  "event_type::birthday": "Ulang tahun",
  "event_type::corporate": "Korporat",
  "event_type::engagement": "Lamaran",
  "event_type::festival": "Festival",
  "event_type::private-party": "Pesta privat",
  "event_type::wedding": "Pernikahan",
  "facilities::air-conditioned-rooms": "Kamar ber-AC",
  "facilities::boarding": "Penitipan",
  "facilities::changing-room": "Ruang ganti",
  "facilities::coworking-space": "Coworking space",
  "facilities::equipment-rental": "Sewa peralatan",
  "facilities::exercise": "Olahraga",
  "facilities::gym": "Gym",
  "facilities::kitchen": "Dapur",
  "facilities::laundry": "Laundry",
  "facilities::meals": "Makanan",
  "facilities::outdoor-area": "Area luar",
  "facilities::playground": "Taman bermain",
  "facilities::pool": "Kolam",
  "facilities::restaurant": "Restoran",
  "facilities::sauna": "Sauna",
  "facilities::shower": "Pancuran",
  "facilities::spa": "Spa",
  "facilities::sports": "Olahraga",
  "facilities::transport": "Transportasi",
  "facilities::webcam": "Webcam",
  "facility::ambulance": "Ambulans",
  "facility::atm": "ATM",
  "facility::cash-deposit": "Setoran tunai",
  "facility::emergency-room": "IGD",
  "facility::foreign-exchange": "Valuta asing",
  "facility::inpatient-care": "Rawat inap",
  "facility::international-transfer": "Transfer internasional",
  "facility::pharmacy": "Apotek",
  "features::coworking-friendly": "Ramah coworking",
  "features::custom-orders": "Pesanan kustom",
  "features::door-to-door": "Pintu ke pintu",
  "features::family-friendly": "Ramah keluarga",
  "features::gift-wrapping": "Bungkus kado",
  "features::live-music": "Musik live",
  "features::ocean-view": "Pemandangan laut",
  "features::pickup": "Ambil sendiri",
  "features::proof-of-delivery": "Bukti pengiriman",
  "features::romantic": "Romantis",
  "features::tax-free-shopping": "Belanja bebas pajak",
  "features::tracking": "Pelacakan",
  "financial_product::bank-account": "Rekening bank",
  "financial_product::insurance": "Asuransi",
  "financial_product::investment": "Investasi",
  "financial_product::loan": "Pinjaman",
  "financial_product::payment-processing": "Pemrosesan pembayaran",
  "fitness_type::crossfit": "CrossFit",
  "fitness_type::gym": "Gym",
  "fitness_type::martial-arts": "Bela diri",
  "fitness_type::personal-training": "Pelatihan personal",
  "fitness_type::pilates": "Pilates",
  "fitness_type::yoga": "Yoga",
  "food_type::barbecue": "Bakar",
  "food_type::coffee": "Kopi",
  "food_type::desserts": "Dessert",
  "food_type::healthy-food": "Makanan sehat",
  "food_type::seafood": "Seafood",
  "food_type::street-food": "Makanan jalanan",
  "format::group": "Grup",
  "format::hybrid": "Hibrida",
  "format::in-person": "Tatap muka",
  "format::large-group": "Grup besar",
  "format::online": "Daring",
  "format::private": "Privat",
  "format::self-guided": "Mandiri",
  "format::small-group": "Grup kecil",
  "frequency::contract": "Kontrak",
  "frequency::monthly": "Bulanan",
  "frequency::one-time": "Sekali",
  "frequency::weekly": "Mingguan",
  "fuel_type::diesel": "Solar",
  "fuel_type::electric": "Listrik",
  "fuel_type::hybrid": "Hibrida",
  "fuel_type::petrol": "Bensin",
  "hours::24-hour-clinic": "Klinik 24 jam",
  "hours::24-hour-pharmacy": "Apotek 24 jam",
  "hours::after-hours-doctor": "Dokter di luar jam",
  "included::entrance-fees": "Tiket masuk",
  "included::equipment": "Peralatan",
  "included::guide": "Pemandu",
  "included::insurance": "Asuransi",
  "included::meals": "Makanan",
  "included::transport": "Transportasi",
  "industry::construction": "Konstruksi",
  "industry::healthcare": "Kesehatan",
  "industry::hospitality": "Perhotelan",
  "industry::retail": "Ritel",
  "industry::technology": "Teknologi",
  "industry::tourism": "Pariwisata",
  "insurance::bpjs": "BPJS",
  "insurance::international-insurance": "Asuransi internasional",
  "insurance::private-insurance": "Asuransi swasta",
  "insurance::self-pay": "Bayar sendiri",
  "land_area::1-5-are": "1–5 are",
  "land_area::5-plus-are": "5+ are",
  "land_area::under-1-are": "Di bawah 1 are",
  "language_of_instruction::bilingual": "Dwi bahasa",
  "language_of_instruction::english": "Inggris",
  "language_of_instruction::indonesian": "Indonesia",
  "language_of_instruction::other": "Lainnya",
  "languages::balinese": "Bali",
  "languages::english": "Inggris",
  "languages::indonesian": "Indonesia",
  "languages::japanese": "Jepang",
  "languages::mandarin": "Mandarin",
  "languages::other": "Lainnya",
  "legal_specialty::commercial": "Komersial",
  "legal_specialty::criminal": "Pidana",
  "legal_specialty::employment": "Ketenagakerjaan",
  "legal_specialty::family": "Keluarga",
  "legal_specialty::immigration": "Imigrasi",
  "legal_specialty::property": "Properti",
  "licensing::commercial-use": "Pemakaian komersial",
  "licensing::full-usage-rights": "Hak pakai penuh",
  "licensing::personal-use": "Pemakaian pribadi",
  "location::city": "Kota",
  "location::client-location": "Lokasi klien",
  "location::destination": "Destinasi",
  "location::district": "Kecamatan",
  "location::island": "Pulau",
  "location::outdoor": "Luar ruangan",
  "location::province": "Provinsi",
  "location::regency": "Kabupaten",
  "location::studio": "Studio",
  "location::village": "Desa",
  "location_feature::beachfront": "Tepi pantai",
  "location_feature::city-center": "Pusat kota",
  "location_feature::near-airport": "Dekat bandara",
  "location_feature::ocean-view": "Pemandangan laut",
  "location_feature::rural": "Pedesaan",
  "materials::custom-made": "Buatan kustom",
  "materials::customer-supplied": "Disediakan pelanggan",
  "materials::imported": "Impor",
  "materials::included": "Termasuk",
  "materials::local": "Lokal",
  "materials::optional": "Opsional",
  "materials::sustainable": "Berkelanjutan",
  "meal::breakfast": "Sarapan",
  "meal::brunch": "Brunch",
  "meal::dinner": "Makan malam",
  "meal::late-night": "Larut malam",
  "meal::lunch": "Makan siang",
  "meal_plan::breakfast-included": "Termasuk sarapan",
  "meal_plan::full-board": "Full-board",
  "meal_plan::half-board": "Half-board",
  "meal_plan::self-catering": "Masak sendiri",
  "membership::annual": "Tahunan",
  "membership::day-pass": "Tiket harian",
  "membership::drop-in": "Datang langsung",
  "membership::monthly": "Bulanan",
  "membership::weekly": "Mingguan",
  "nightly_price::1-5m-3m": "Rp 1,5 jt–3 jt",
  "nightly_price::3m-plus": "Rp 3 jt+",
  "nightly_price::500k-1-5m": "Rp 500 rb–1,5 jt",
  "nightly_price::under-500k": "Di bawah Rp 500 rb",
  "origin::handmade": "Buatan tangan",
  "origin::imported": "Impor",
  "origin::indonesian-brands": "Merek Indonesia",
  "origin::locally-made": "Buatan lokal",
  "package::all-inclusive": "All-inclusive",
  "package::custom-package": "Paket kustom",
  "package::full-day": "Seharian",
  "package::half-day": "Setengah hari",
  "package::hourly": "Per jam",
  "package::project-package": "Paket proyek",
  "package::venue-only": "Venue saja",
  "parking::car-parking": "Parkir mobil",
  "parking::motorcycle-parking": "Parkir motor",
  "parking::street-parking": "Parkir pinggir jalan",
  "parking::valet": "Valet",
  "parts::aftermarket": "Aftermarket",
  "parts::oem-compatible": "Kompatibel OEM",
  "parts::original": "Asli",
  "parts::refurbished": "Rekondisi",
  "parts::special-order": "Pesanan khusus",
  "parts::used": "Bekas",
  "patient_type::adults": "Dewasa",
  "patient_type::children": "Anak-anak",
  "patient_type::international-patients": "Pasien internasional",
  "patient_type::seniors": "Lansia",
  "patient_type::women": "Perempuan",
  "payments::bank-transfer": "Transfer bank",
  "payments::business-account": "Akun bisnis",
  "payments::cards": "Kartu",
  "payments::cash": "Tunai",
  "payments::cash-on-delivery": "Bayar di tempat",
  "payments::e-wallet": "Dompet digital",
  "payments::installments": "Cicilan",
  "payments::prepaid": "Prabayar",
  "payments::qris": "QRIS",
  "pet_size::large": "Besar",
  "pet_size::medium": "Sedang",
  "pet_size::small": "Kecil",
  "pickup::airport-pickup": "Jemput bandara",
  "pickup::hotel-pickup": "Jemput hotel",
  "pickup::meeting-point": "Titik kumpul",
  "planning_level::day-of-coordination": "Koordinasi hari-H",
  "planning_level::full-planning": "Perencanaan penuh",
  "planning_level::partial-planning": "Perencanaan sebagian",
  "policies::children-allowed": "Anak diizinkan",
  "policies::free-cancellation": "Batal gratis",
  "policies::long-stays": "Menginap lama",
  "policies::pay-at-property": "Bayar di properti",
  "policies::pets-allowed": "Hewan diizinkan",
  "practitioner::certified-trainer": "Pelatih bersertifikat",
  "practitioner::licensed-therapist": "Terapis berizin",
  "practitioner::medical-practitioner": "Tenaga medis",
  "price_level::budget": "Hemat",
  "price_level::luxury": "Mewah",
  "price_level::mid-range": "Menengah",
  "price_level::moderate": "Sedang",
  "price_level::premium": "Premium",
  "pricing::fixed-price": "Harga tetap",
  "pricing::fixed-project": "Proyek tetap",
  "pricing::free-consultation": "Konsultasi gratis",
  "pricing::free-estimate": "Estimasi gratis",
  "pricing::hourly": "Per jam",
  "pricing::hourly-rate": "Tarif per jam",
  "pricing::inspection-fee": "Biaya inspeksi",
  "pricing::subscription": "Langganan",
  "product_type::beauty": "Kecantikan",
  "product_type::books": "Buku",
  "product_type::electronics": "Elektronik",
  "product_type::fashion": "Fesyen",
  "product_type::grocery": "Sembako",
  "product_type::handicrafts": "Kerajinan",
  "product_type::jewelry": "Perhiasan",
  "production::editing": "Penyuntingan",
  "production::full-production": "Produksi penuh",
  "production::pre-production": "Pra-produksi",
  "production::shooting": "Pengambilan gambar",
  "professional_type::architect": "Arsitek",
  "professional_type::contractor": "Kontraktor",
  "professional_type::engineer": "Insinyur",
  "professional_type::interior-designer": "Desainer interior",
  "professional_type::surveyor": "Surveyor",
  "project_type::commercial": "Komersial",
  "project_type::hospitality": "Perhotelan",
  "project_type::industrial": "Industri",
  "project_type::residential": "Hunian",
  "project_type::retail": "Ritel",
  "promotions::discounts": "Diskon",
  "promotions::free-consultation": "Konsultasi gratis",
  "promotions::loyalty-program": "Program loyalitas",
  "promotions::packages": "Paket",
  "property_features::beachfront": "Tepi pantai",
  "property_features::furnished": "Berperabot",
  "property_features::garden": "Taman",
  "property_features::ocean-view": "Pemandangan laut",
  "property_features::parking": "Parkir",
  "property_features::pool": "Kolam",
  "property_type::apartment": "Apartemen",
  "property_type::commercial-property": "Properti komersial",
  "property_type::glamping": "Glamping",
  "property_type::guesthouse": "Guest house",
  "property_type::homestay": "Homestay",
  "property_type::hostel": "Hostel",
  "property_type::hotel": "Hotel",
  "property_type::house": "Rumah",
  "property_type::kos": "Kos",
  "property_type::land": "Tanah",
  "property_type::office": "Kantor",
  "property_type::resort": "Resor",
  "property_type::restaurant": "Restoran",
  "property_type::retail": "Ritel",
  "property_type::villa": "Villa",
  "property_type::warehouse": "Gudang",
  "protection::fragile-handling": "Penanganan rapuh",
  "protection::insurance": "Asuransi",
  "protection::secure-transport": "Transportasi aman",
  "provider_preference::female-practitioner": "Praktisi perempuan",
  "provider_preference::male-practitioner": "Praktisi laki-laki",
  "rating::3-plus": "3+",
  "rating::4-5-plus": "4.5+",
  "rating::4-plus": "4+",
  "rental_features::helmet-included": "Termasuk helm",
  "rental_features::insurance-included": "Termasuk asuransi",
  "rental_features::unlimited-mileage": "Kilometer bebas",
  "rental_features::vehicle-delivery": "Antar kendaraan",
  "rental_type::daily": "Harian",
  "rental_type::furniture": "Furnitur",
  "rental_type::lighting": "Pencahayaan",
  "rental_type::monthly": "Bulanan",
  "rental_type::self-drive": "Supir sendiri",
  "rental_type::sound-systems": "Sistem suara",
  "rental_type::tableware": "Peralatan makan",
  "rental_type::tents": "Tenda",
  "rental_type::weekly": "Mingguan",
  "rental_type::with-driver": "Dengan sopir",
  "repair_service::ac": "AC",
  "repair_service::battery": "Aki",
  "repair_service::bodywork": "Bodi",
  "repair_service::brakes": "Rem",
  "repair_service::electrical": "Kelistrikan",
  "repair_service::engine": "Mesin",
  "repair_service::tires": "Ban",
  "requirements::sterilized-pets-only": "Hanya hewan steril",
  "requirements::temperament-assessment": "Penilaian temperamen",
  "requirements::vaccination-required": "Wajib vaksin",
  "response::emergency-service": "Layanan darurat",
  "response::roadside-assistance": "Bantuan jalan",
  "response::same-day-repair": "Servis hari ini",
  "response_time::same-day": "Hari yang sama",
  "response_time::scheduled": "Terjadwal",
  "response_time::within-24-hours": "Dalam 24 jam",
  "returns::exchange-only": "Tukar saja",
  "returns::final-sale": "Tidak dapat dikembalikan",
  "returns::returns-accepted": "Pengembalian diterima",
  "room_type::entire-property": "Seluruh properti",
  "room_type::family-room": "Kamar keluarga",
  "room_type::private-room": "Kamar privat",
  "room_type::shared-room": "Kamar bersama",
  "room_type::suite": "Suite",
  "schedule::evenings": "Malam",
  "schedule::intensive": "Intensif",
  "schedule::weekdays": "Hari kerja",
  "schedule::weekends": "Akhir pekan",
  "service::ac": "AC",
  "service::accounting": "Akuntansi",
  "service::aesthetics": "Estetika",
  "service::audio": "Audio",
  "service::banking": "Perbankan",
  "service::barbering": "Pangkas rambut",
  "service::battery-replacement": "Ganti baterai",
  "service::boarding": "Penitipan",
  "service::branding": "Branding",
  "service::cleaning": "Kebersihan",
  "service::company-law": "Hukum perusahaan",
  "service::construction": "Konstruksi",
  "service::consulting": "Konsultasi",
  "service::content-production": "Produksi konten",
  "service::coordination": "Koordinasi",
  "service::courier": "Kurir",
  "service::customs": "Bea cukai",
  "service::data-recovery": "Pemulihan data",
  "service::daycare": "Daycare",
  "service::decor": "Dekorasi",
  "service::design": "Desain",
  "service::diagnostics": "Diagnostik",
  "service::drone": "Drone",
  "service::electrical": "Kelistrikan",
  "service::entertainment": "Hiburan",
  "service::financing": "Pembiayaan",
  "service::freight": "Kargo",
  "service::fulfillment": "Fulfillment",
  "service::graphic-design": "Desain grafis",
  "service::grooming": "Grooming",
  "service::hair": "Rambut",
  "service::insurance": "Asuransi",
  "service::landscaping": "Lansekap",
  "service::lashes": "Bulu mata",
  "service::laundry": "Laundry",
  "service::legal-advice": "Nasihat hukum",
  "service::licensing": "Perizinan",
  "service::local-delivery": "Pengiriman lokal",
  "service::management": "Manajemen",
  "service::marketing": "Pemasaran",
  "service::massage": "Pijat",
  "service::moving": "Pindahan",
  "service::nails": "Kuku",
  "service::notary": "Notaris",
  "service::pest-control": "Pengendalian hama",
  "service::photography": "Fotografi",
  "service::planning": "Perencanaan",
  "service::plumbing": "Pipa",
  "service::property-law": "Hukum properti",
  "service::recruitment": "Rekrutmen",
  "service::renovation": "Renovasi",
  "service::rental": "Sewa",
  "service::rentals": "Sewa",
  "service::retail": "Ritel",
  "service::sale": "Penjualan",
  "service::screen-repair": "Servis layar",
  "service::skincare": "Perawatan kulit",
  "service::software-repair": "Servis perangkat lunak",
  "service::tattoo": "Tato",
  "service::tax": "Pajak",
  "service::training": "Pelatihan",
  "service::translation": "Terjemahan",
  "service::venue": "Venue",
  "service::veterinary": "Hewan",
  "service::video": "Video",
  "service::walking": "Jalan kaki",
  "service::warehousing": "Pergudangan",
  "service_mode::at-clinic": "Di klinik",
  "service_mode::at-location": "Di lokasi",
  "service_mode::delivery": "Pengiriman",
  "service_mode::home-service": "Layanan ke rumah",
  "service_mode::home-visit": "Kunjungan rumah",
  "service_mode::hotel-service": "Layanan hotel",
  "service_mode::in-person": "Tatap muka",
  "service_mode::mobile-service": "Layanan keliling",
  "service_mode::on-site": "Di lokasi",
  "service_mode::online": "Daring",
  "service_mode::outdoor-class": "Kelas luar ruangan",
  "service_mode::pickup": "Ambil sendiri",
  "service_mode::pickup-and-delivery": "Ambil dan antar",
  "service_mode::remote-assessment": "Penilaian jarak jauh",
  "service_mode::studio": "Studio",
  "session_type::couples": "Pasangan",
  "session_type::group": "Grup",
  "session_type::private": "Privat",
  "setting::beachfront": "Tepi pantai",
  "setting::garden": "Taman",
  "setting::hotel": "Hotel",
  "setting::indoor": "Dalam ruangan",
  "setting::outdoor": "Luar ruangan",
  "setting::poolside": "Tepi kolam",
  "setting::restaurant": "Restoran",
  "setting::rooftop": "Rooftop",
  "setting::villa": "Villa",
  "shipment::commercial-cargo": "Kargo komersial",
  "shipment::documents": "Dokumen",
  "shipment::food": "Makanan",
  "shipment::furniture": "Furnitur",
  "shipment::parcels": "Paket",
  "shipment::vehicles": "Kendaraan",
  "shopping_mode::click-and-collect": "Pesan dan ambil",
  "shopping_mode::delivery": "Pengiriman",
  "shopping_mode::in-store": "Di toko",
  "shopping_mode::online": "Daring",
  "skill_level::advanced": "Mahir",
  "skill_level::beginner": "Pemula",
  "skill_level::intermediate": "Menengah",
  "special_handling::frozen": "Beku",
  "special_handling::hazardous": "Berbahaya",
  "special_handling::oversized": "Ukuran besar",
  "special_handling::refrigerated": "Berpendingin",
  "specialization::appliances": "Peralatan rumah",
  "specialization::foreign-owned-company": "Perusahaan asing",
  "specialization::local-company": "Perusahaan lokal",
  "specialization::permits": "Izin",
  "specialization::pool": "Kolam",
  "specialization::pt-pma": "PT PMA",
  "specialization::security-systems": "Sistem keamanan",
  "specialization::septic-system": "Septik tank",
  "specialization::solar": "Surya",
  "specialization::visas": "Visa",
  "specialty::commercial": "Komersial",
  "specialty::dental": "Gigi",
  "specialty::eye-care": "Perawatan mata",
  "specialty::fashion": "Fesyen",
  "specialty::food": "Makanan",
  "specialty::general-practice": "Praktik umum",
  "specialty::maternity": "Kebidanan",
  "specialty::mental-health": "Kesehatan jiwa",
  "specialty::pediatrics": "Anak",
  "specialty::physiotherapy": "Fisioterapi",
  "specialty::portrait": "Potret",
  "specialty::product": "Produk",
  "specialty::property": "Properti",
  "specialty::wedding": "Pernikahan",
  "speed::instant": "Instan",
  "speed::next-day": "Keesokan hari",
  "speed::same-day": "Hari yang sama",
  "speed::scheduled": "Terjadwal",
  "speed::standard": "Standar",
  "star_rating::1": "1 bintang",
  "star_rating::2": "2 bintang",
  "star_rating::3": "3 bintang",
  "star_rating::4": "4 bintang",
  "star_rating::5": "5 bintang",
  "star_rating::unrated": "Tanpa bintang",
  "stay_features::connecting-rooms": "Kamar penghubung",
  "stay_features::day-use-rooms": "Kamar harian",
  "stay_features::monthly-rates": "Tarif bulanan",
  "stay_features::private-pool": "Kolam privat",
  "style::cinematic": "Sinematik",
  "style::documentary": "Dokumenter",
  "style::editorial": "Editorial",
  "style::indonesian": "Indonesia",
  "style::intimate": "Intim",
  "style::lifestyle": "Gaya hidup",
  "style::luxury": "Mewah",
  "style::modern": "Modern",
  "style::traditional": "Tradisional",
  "style::traditional-balinese": "Tradisional Bali",
  "style::western": "Barat",
  "subject::arts": "Seni",
  "subject::business": "Bisnis",
  "subject::languages": "Bahasa",
  "subject::mathematics": "Matematika",
  "subject::music": "Musik",
  "subject::science": "Sains",
  "subject::technology": "Teknologi",
  "support::placement-testing": "Tes penempatan",
  "support::special-needs-support": "Dukungan kebutuhan khusus",
  "support::trial-class": "Kelas percobaan",
  "support::tutoring": "Bimbingan belajar",
  "support_type::on-site": "Di lokasi",
  "support_type::pickup-and-delivery": "Ambil dan antar",
  "support_type::remote": "Jarak jauh",
  "support_type::walk-in": "Tanpa janji",
  "sustainability::fair-trade": "Perdagangan adil",
  "sustainability::plastic-free": "Tanpa plastik",
  "sustainability::recycled": "Daur ulang",
  "sustainability::refillable": "Isi ulang",
  "transaction::for-sale": "Dijual",
  "transaction::freehold": "Hak milik",
  "transaction::leasehold": "Hak sewa",
  "transaction::long-term-rent": "Sewa jangka panjang",
  "transaction::short-term-rent": "Sewa jangka pendek",
  "transmission::automatic": "Otomatis",
  "transmission::manual": "Manual",
  "transport::air-freight": "Kargo udara",
  "transport::airport-transfer": "Antar-jemput bandara",
  "transport::car": "Mobil",
  "transport::car-rental": "Sewa mobil",
  "transport::motorcycle": "Motor",
  "transport::scooter-rental": "Sewa skuter",
  "transport::sea-freight": "Kargo laut",
  "transport::shuttle": "Shuttle",
  "transport::truck": "Truk",
  "transport::van": "Van",
  "transport_route::airport": "Bandara",
  "transport_route::intercity": "Antarkota",
  "transport_route::island-transfer": "Transfer pulau",
  "transport_route::local": "Lokal",
  "treatment_style::luxury": "Mewah",
  "treatment_style::medical": "Medis",
  "treatment_style::organic": "Organik",
  "treatment_style::therapeutic": "Terapeutik",
  "treatment_style::traditional-balinese": "Tradisional Bali",
  "turnaround::1-3-days": "1–3 hari",
  "turnaround::1-4-weeks": "1–4 minggu",
  "turnaround::same-day": "Hari yang sama",
  "turnaround::special-order": "Pesanan khusus",
  "turnaround::under-one-week": "Di bawah satu minggu",
  "turnaround::while-you-wait": "Sambil menunggu",
  "urgency::emergency-24-hour": "Darurat 24 jam",
  "urgency::same-day": "Hari yang sama",
  "urgency::scheduled": "Terjadwal",
  "vehicle_type::car": "Mobil",
  "vehicle_type::electric-vehicle": "Kendaraan listrik",
  "vehicle_type::minibus": "Minibus",
  "vehicle_type::motorcycle": "Motor",
  "vehicle_type::scooter": "Skuter",
  "vehicle_type::truck": "Truk",
  "vehicle_type::van": "Van",
  "verification::claimed-listing": "Listing diklaim",
  "verification::verified-address": "Alamat terverifikasi",
  "verification::verified-business": "Bisnis terverifikasi",
  "veterinary_specialty::dental": "Gigi",
  "veterinary_specialty::emergency": "Darurat",
  "veterinary_specialty::general": "Umum",
  "veterinary_specialty::surgery": "Bedah",
  "veterinary_specialty::vaccination": "Vaksinasi",
  "warranty::manufacturer-warranty": "Garansi pabrik",
  "warranty::parts-warranty": "Garansi suku cadang",
  "warranty::repair-warranty": "Garansi servis",
  "warranty::service-warranty": "Garansi layanan",
  "warranty::store-warranty": "Garansi toko",
  "weight::20-100kg": "20–100 kg",
  "weight::5-20kg": "5–20 kg",
  "weight::freight": "Kargo",
  "weight::under-5kg": "Di bawah 5 kg",
  "workshop_type::authorized-dealer": "Dealer resmi",
  "workshop_type::independent-workshop": "Bengkel independen",
  "workshop_type::mobile-mechanic": "Mekanik keliling",
};

