/**
 * Indonesian labels for taxonomy slugs. English `label` on TAXONOMY stays
 * canonical for slugs and search; public `/id` pages use these strings.
 */
export const CATEGORY_LABELS_ID: Record<string, string> = {
  "food-drink": "Makanan & minuman",
  restaurants: "Restoran",
  "warungs-local-food": "Warung & makanan lokal",
  "cafes-coffee-shops": "Kafe & kedai kopi",
  "bakeries-cake-shops": "Toko roti & kue",
  "bars-pubs": "Bar & pub",
  "beach-clubs": "Beach club",
  "catering-services": "Katering",
  "fast-food-takeaway": "Cepat saji & bungkus",
  "food-stalls-street-food": "Kaki lima & makanan jalanan",
  "seafood-restaurants": "Restoran seafood",
  "vegetarian-vegan-dining": "Masakan vegetarian & vegan",
  "dessert-ice-cream-shops": "Dessert & es krim",
  "hotels-accommodation": "Hotel & akomodasi",
  hotels: "Hotel",
  resorts: "Resor",
  villas: "Villa",
  "guesthouses-homestays": "Guest house & homestay",
  hostels: "Hostel",
  "bungalows-cottages": "Bungalow & cottage",
  "apartments-serviced-residences": "Apartemen & hunian servis",
  "vacation-rentals": "Sewa liburan",
  "kos-long-term-rentals": "Kos & sewa jangka panjang",
  "camping-glamping": "Camping & glamping",
  "travel-experiences": "Perjalanan & pengalaman",
  "travel-agencies": "Biro perjalanan",
  "tour-operators-local-guides": "Operator tur & pemandu lokal",
  "tourist-attractions": "Tempat wisata",
  "cultural-experiences": "Pengalaman budaya",
  "diving-snorkeling": "Diving & snorkling",
  "surf-schools-rentals": "Sekolah & sewa selancar",
  "boat-charters-island-transfers": "Sewa kapal & transfer pulau",
  "water-sports": "Olahraga air",
  "hiking-adventure-tours": "Hiking & tur petualangan",
  "retreats-wellness-experiences": "Retreat & wellness",
  "transport-automotive": "Transportasi & otomotif",
  "car-rentals": "Sewa mobil",
  "motorcycle-scooter-rentals": "Sewa motor & skuter",
  "taxis-private-drivers": "Taksi & sopir pribadi",
  "airport-transfers-shuttles": "Antar-jemput bandara",
  "car-repair-shops": "Bengkel mobil",
  "motorcycle-repair-shops": "Bengkel motor",
  "car-motorcycle-washes": "Cuci mobil & motor",
  "tires-batteries-spare-parts": "Ban, aki & suku cadang",
  "towing-roadside-assistance": "Derek & bantuan jalan",
  "automotive-ac-services": "Servis AC mobil",
  "fuel-stations-ev-charging": "SPBU & pengisian EV",
  "health-medical": "Kesehatan & medis",
  "clinics-hospitals": "Klinik & rumah sakit",
  pharmacies: "Apotek",
  "dentists-dental-clinics": "Dokter gigi & klinik gigi",
  "eye-clinics-opticians": "Klinik mata & optik",
  "medical-laboratories": "Laboratorium medis",
  "physiotherapy-rehabilitation": "Fisioterapi & rehabilitasi",
  "mental-health-counseling": "Kesehatan jiwa & konseling",
  "maternity-womens-health": "Kesehatan ibu & perempuan",
  "home-nursing-elder-care": "Perawat rumah & lansia",
  "traditional-holistic-medicine": "Pengobatan tradisional",
  "beauty-spa-fitness": "Kecantikan, spa & kebugaran",
  "beauty-aesthetic-clinics": "Klinik kecantikan & estetika",
  "hair-salons-barbers": "Salon & pangkas rambut",
  "spas-massage": "Spa & pijat",
  "nail-lash-brow-studios": "Studio kuku, bulu mata & alis",
  "gyms-fitness-centers": "Gym & pusat kebugaran",
  "yoga-pilates-studios": "Studio yoga & pilates",
  "personal-trainers": "Pelatih kebugaran",
  "wellness-centers-saunas": "Pusat wellness & sauna",
  "tattoo-piercing-studios": "Studio tato & tindik",
  "nutrition-wellness-coaching": "Nutrisi & coaching wellness",
  "home-services": "Layanan rumah",
  "ac-installation-repair": "Pemasangan & servis AC",
  "home-cleaning-services": "Jasa kebersihan rumah",
  "laundry-dry-cleaning": "Laundry & dry clean",
  "handyman-services": "Tukang serabutan",
  "plumbing-services": "Jasa pipa",
  "electrical-services": "Jasa listrik",
  "appliance-repair": "Servis peralatan rumah",
  "pest-control": "Pengendalian hama",
  "septic-tank-cleaning": "Sedot WC",
  "moving-services": "Jasa pindahan",
  "gardening-landscaping": "Taman & lansekap",
  "pool-maintenance": "Perawatan kolam",
  "security-cctv-installation": "Keamanan & pasang CCTV",
  "waste-removal-recycling": "Angkut sampah & daur ulang",
  "property-construction": "Properti & konstruksi",
  "real-estate-agents": "Agen properti",
  "property-developers": "Pengembang properti",
  "property-management": "Manajemen properti",
  "building-contractors": "Kontraktor bangunan",
  "renovation-services": "Jasa renovasi",
  architects: "Arsitek",
  "interior-designers": "Desainer interior",
  "surveyors-engineering-services": "Surveyor & teknik",
  "building-materials-stores": "Toko bahan bangunan",
  "hardware-tool-stores": "Toko perkakas",
  "furniture-home-decor": "Furnitur & dekorasi",
  "solar-renewable-energy-services": "Surya & energi terbarukan",
  "business-professional-services": "Layanan bisnis & profesional",
  "accounting-bookkeeping": "Akuntansi & pembukuan",
  "tax-consultants": "Konsultan pajak",
  "business-consultants": "Konsultan bisnis",
  "company-formation-licensing": "Pendirian PT & perizinan",
  "immigration-visa-services": "Imigrasi & visa",
  "hr-recruitment": "HR & rekrutmen",
  "coworking-spaces": "Coworking space",
  "translation-interpreting": "Terjemahan & juru bahasa",
  "marketing-advertising-agencies": "Agensi pemasaran & iklan",
  "copy-print-shops": "Fotokopi & percetakan",
  "office-supplies": "Alat tulis kantor",
  "business-security-services": "Keamanan bisnis",
  "legal-financial-services": "Hukum & keuangan",
  "law-firms-legal-services": "Kantor hukum",
  "notaries-ppat": "Notaris & PPAT",
  "banks-atms": "Bank & ATM",
  "money-changers": "Penukaran uang",
  "insurance-services": "Asuransi",
  "loans-financing": "Pinjaman & pembiayaan",
  "financial-advisors": "Penasihat keuangan",
  "payment-pos-services": "Pembayaran & POS",
  "investment-wealth-services": "Investasi & kekayaan",
  "shopping-retail": "Belanja & ritel",
  "supermarkets-grocery-stores": "Supermarket & minimarket",
  "convenience-stores": "Toko kelontong",
  "traditional-markets": "Pasar tradisional",
  "fashion-clothing": "Fesyen & pakaian",
  "jewelry-accessories": "Perhiasan & aksesori",
  "souvenirs-handicrafts": "Suvenir & kerajinan",
  "electronics-appliances": "Elektronik & peralatan",
  "mobile-phones-accessories": "HP & aksesoris",
  "beauty-cosmetics": "Kecantikan & kosmetik",
  "baby-childrens-stores": "Toko bayi & anak",
  "sports-outdoor-stores": "Toko olahraga & outdoor",
  "books-stationery": "Buku & alat tulis",
  "florists-plant-shops": "Florist & tanaman",
  "technology-repair": "Teknologi & servis",
  "phone-device-repair": "Servis HP",
  "computer-laptop-repair": "Servis komputer & laptop",
  "electronics-repair": "Servis elektronik",
  "it-support": "Dukungan IT",
  "internet-network-installation": "Pemasangan internet & jaringan",
  "data-recovery": "Pemulihan data",
  "cybersecurity-services": "Keamanan siber",
  "web-app-development": "Pengembangan web & aplikasi",
  "software-digital-services": "Perangkat lunak & layanan digital",
  "smart-home-installation": "Pemasangan smart home",
  "creative-media": "Kreatif & media",
  "photography-studios": "Studio fotografi",
  "commercial-photography": "Fotografi komersial",
  "video-production": "Produksi video",
  "drone-photography": "Fotografi drone",
  "graphic-design-branding": "Desain grafis & branding",
  "content-social-media-services": "Konten & media sosial",
  "printing-signage": "Percetakan & papan nama",
  "audio-recording-studios": "Studio rekaman",
  "media-publishing": "Media & penerbitan",
  "advertising-production": "Produksi iklan",
  "education-childcare": "Pendidikan & pengasuhan",
  "preschools-daycare": "PAUD & daycare",
  "primary-secondary-schools": "SD & sekolah menengah",
  "universities-colleges": "Universitas & perguruan tinggi",
  "tutoring-learning-centers": "Bimbingan belajar",
  "language-schools": "Kursus bahasa",
  "vocational-skills-training": "Pelatihan kejuruan",
  "music-dance-art-schools": "Sekolah musik, tari & seni",
  "driving-schools": "Kursus mengemudi",
  "special-needs-education": "Pendidikan kebutuhan khusus",
  "online-courses-training": "Kursus & pelatihan daring",
  "events-weddings": "Acara & pernikahan",
  "wedding-planners": "Wedding organizer",
  "event-organizers": "Event organizer",
  "wedding-event-venues": "Venue pernikahan & acara",
  "event-decorators": "Dekorasi acara",
  "bridal-wear": "Busana pengantin",
  "djs-bands-entertainers": "DJ, band & penghibur",
  "party-equipment-rental": "Sewa peralatan pesta",
  "invitations-event-souvenirs": "Undangan & suvenir acara",
  "ceremony-officiant-services": "Upacara & penghulu",
  "event-staffing": "Staf acara",
  "pets-animals": "Hewan & peliharaan",
  "veterinary-clinics": "Klinik hewan",
  "pet-grooming": "Grooming hewan",
  "pet-boarding-hotels": "Penitipan & hotel hewan",
  "pet-sitting-dog-walking": "Penitipan & jalan anjing",
  "pet-stores-supplies": "Toko & perlengkapan hewan",
  "pet-training": "Pelatihan hewan",
  "animal-rescue-adoption": "Penyelamatan & adopsi hewan",
  "livestock-animal-services": "Ternak & layanan hewan",
  "logistics-delivery": "Logistik & pengiriman",
  "courier-parcel-delivery": "Kurir & paket",
  "local-delivery-services": "Pengiriman lokal",
  "cargo-freight": "Kargo & kargo laut",
  "warehousing-storage": "Gudang & penyimpanan",
  "fulfillment-services": "Fulfillment",
  "shipping-customs-agents": "Pengiriman & bea cukai",
  "postal-services": "Layanan pos",
  "refrigerated-cold-chain-delivery": "Pengiriman berpendingin",
};

/** Display names for Events related-service pointers (`related[].as`). */
export const RELATED_AS_ID: Record<string, string> = {
  Catering: "Katering",
  Photography: "Fotografi",
  Makeup: "Rias",
  Florists: "Florist",
  Cakes: "Kue",
};
